<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DefectoCamaraTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('defecto_camara')->delete();
        
        \DB::table('defecto_camara')->insert(array (
            0 => 
            array (
                'id' => 1,
                'codigo' => '103',
                'descripcion' => 'Ampollas En El Cuerpo De La Cámara',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            1 => 
            array (
                'id' => 2,
                'codigo' => '152',
                'descripcion' => 'Ajuste Comercial',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            2 => 
            array (
                'id' => 3,
                'codigo' => '222',
                'descripcion' => 'Sin Garantía Según Factura De Venta',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            3 => 
            array (
                'id' => 4,
                'codigo' => '229',
                'descripcion' => 'Fuera De Garantía Por Lote De Fábrica',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            4 => 
            array (
                'id' => 5,
                'codigo' => '237',
                'descripcion' => 'Material Degradado Por Mal Almacenamiento',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            5 => 
            array (
                'id' => 6,
                'codigo' => '902',
                'descripcion' => 'Empate Pegado',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            6 => 
            array (
                'id' => 7,
                'codigo' => '903',
                'descripcion' => 'Empate Agrietado',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            7 => 
            array (
                'id' => 8,
                'codigo' => '904',
                'descripcion' => 'Empate Con Rebaba',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            8 => 
            array (
                'id' => 9,
                'codigo' => '912',
                'descripcion' => 'Arruga Longitudinal En El Cuerpo De La Cámara',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            9 => 
            array (
                'id' => 10,
                'codigo' => '913',
                'descripcion' => 'Arruga Diametral O Transversal',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            10 => 
            array (
                'id' => 11,
                'codigo' => '923',
                'descripcion' => 'Debilidad En La Base De La Válvula',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            11 => 
            array (
                'id' => 12,
                'codigo' => '924',
                'descripcion' => 'Punto Débil En El Cuerpo De La Cámara',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            12 => 
            array (
                'id' => 13,
                'codigo' => '925',
                'descripcion' => 'Perforación En Proceso',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            13 => 
            array (
                'id' => 14,
                'codigo' => '930',
                'descripcion' => 'Crudo En Un Sector De La Cámara',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            14 => 
            array (
                'id' => 15,
                'codigo' => '931',
                'descripcion' => 'Crudo En La Base De La Válvula',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            15 => 
            array (
                'id' => 16,
                'codigo' => '932',
                'descripcion' => 'Crudo En Todo El Cuerpo',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            16 => 
            array (
                'id' => 17,
                'codigo' => '933',
                'descripcion' => 'Cámara Mordida',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            17 => 
            array (
                'id' => 18,
                'codigo' => '934',
                'descripcion' => 'Adelgazamiento En La Línea De Registro',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            18 => 
            array (
                'id' => 19,
                'codigo' => '937',
                'descripcion' => 'Hoyuelos En La Cámara - Porosidad',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            19 => 
            array (
                'id' => 20,
                'codigo' => '939',
                'descripcion' => 'Cámara Degradada',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            20 => 
            array (
                'id' => 21,
                'codigo' => '940',
                'descripcion' => 'Dañada - Mala Operación, Transporte en Fábrica',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            21 => 
            array (
                'id' => 22,
                'codigo' => '941',
                'descripcion' => 'Defecto Original De La Válvula',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            22 => 
            array (
                'id' => 23,
                'codigo' => '942',
                'descripcion' => 'Válvula Equivocada',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            23 => 
            array (
                'id' => 24,
                'codigo' => '943',
                'descripcion' => 'Válvula Despegada',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            24 => 
            array (
                'id' => 25,
                'codigo' => '944',
                'descripcion' => 'Válvula con Vástago Dañado',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            25 => 
            array (
                'id' => 26,
                'codigo' => '945',
                'descripcion' => 'Válvula Dañada - Mala Operación',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            26 => 
            array (
                'id' => 27,
                'codigo' => '946',
                'descripcion' => 'Válvula Tapada',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            27 => 
            array (
                'id' => 28,
                'codigo' => '947',
                'descripcion' => 'Válvula Desplazada',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            28 => 
            array (
                'id' => 29,
                'codigo' => '950',
                'descripcion' => 'Crudo En El Borde De La Válvula',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            29 => 
            array (
                'id' => 30,
                'codigo' => '951',
                'descripcion' => 'Ampolla En La Base De Válvula',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            30 => 
            array (
                'id' => 31,
                'codigo' => '952',
                'descripcion' => 'Ampolla En El Empate',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            31 => 
            array (
                'id' => 32,
                'codigo' => '955',
                'descripcion' => 'Molde Perforado',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            32 => 
            array (
                'id' => 33,
                'codigo' => '956',
                'descripcion' => 'Defecto Estético',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            33 => 
            array (
                'id' => 34,
                'codigo' => '957',
                'descripcion' => 'Identificación No Legible',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            34 => 
            array (
                'id' => 35,
                'codigo' => '970',
                'descripcion' => 'Molde Desplazado - Escalón En La Línea De Registro',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            35 => 
            array (
                'id' => 36,
                'codigo' => '8007',
                'descripcion' => 'Error De Asignación Del Rin',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            36 => 
            array (
                'id' => 37,
                'codigo' => '8010',
                'descripcion' => 'Exceso De Temperatura',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            37 => 
            array (
                'id' => 38,
                'codigo' => '9100',
                'descripcion' => 'Desprendimiento De La Válvula',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            38 => 
            array (
                'id' => 39,
                'codigo' => '9101',
                'descripcion' => 'Daño En La Base De La Válvula Por Mal Montaje O Mala Operación',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            39 => 
            array (
                'id' => 40,
                'codigo' => '9102',
                'descripcion' => 'Válvula Dañada Por Máquina De Montaje',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            40 => 
            array (
                'id' => 41,
                'codigo' => '9103',
                'descripcion' => 'Fricción Causada Por La Pestaña Del Talón Del Caucho',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            41 => 
            array (
                'id' => 42,
                'codigo' => '9104',
                'descripcion' => 'Daños Por Defecto Del Caucho',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            42 => 
            array (
                'id' => 43,
                'codigo' => '9105',
                'descripcion' => 'Fricción Causada Por La Liner',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            43 => 
            array (
                'id' => 44,
                'codigo' => '9106',
                'descripcion' => 'Agrietamiento Por Explosión',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            44 => 
            array (
                'id' => 45,
                'codigo' => '9107',
                'descripcion' => 'Grieta Circunferencial Causada Por Protector',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            45 => 
            array (
                'id' => 46,
                'codigo' => '9108',
                'descripcion' => 'Cámara Perforada Por Material Extraño En El Caucho',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            46 => 
            array (
                'id' => 47,
                'codigo' => '9109',
                'descripcion' => 'Rasgadura Causada Por Herramental Durante El Montaje',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            47 => 
            array (
                'id' => 48,
                'codigo' => '9110',
                'descripcion' => 'Estiramiento O Plegaduras',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            48 => 
            array (
                'id' => 49,
                'codigo' => '9111',
                'descripcion' => 'Perforación Por Mal Montaje En Rin Acanalado',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            49 => 
            array (
                'id' => 50,
                'codigo' => '9116',
                'descripcion' => 'Sin Defecto En El Producto',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            50 => 
            array (
                'id' => 51,
                'codigo' => '112A',
                'descripcion' => 'Material Extraño De Extrusión',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            51 => 
            array (
                'id' => 52,
                'codigo' => '112B',
                'descripcion' => 'Material Extraño De Vulcanización',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            52 => 
            array (
                'id' => 53,
                'codigo' => '901A',
                'descripcion' => 'Empate Abierto Entrada Cuchilla',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            53 => 
            array (
                'id' => 54,
                'codigo' => '901B',
                'descripcion' => 'Empate Abierto Entrada Cuchilla /Cambio De Temperatura',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            54 => 
            array (
                'id' => 55,
                'codigo' => '901C',
                'descripcion' => 'Empate Abierto En El Cuerpo Del Tubo',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            55 => 
            array (
                'id' => 56,
                'codigo' => '901D',
                'descripcion' => 'Empate Abierto Salida Cuchilla /Cambio De Temperatura',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            56 => 
            array (
                'id' => 57,
                'codigo' => '901E',
                'descripcion' => 'Empate Abierto Salida Cuchilla',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            57 => 
            array (
                'id' => 58,
                'codigo' => '911A',
                'descripcion' => 'Arruga Longitudinal En La Base De La Válvula; A Los Lados Y En Línea De Registro',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            58 => 
            array (
                'id' => 59,
                'codigo' => '911B',
                'descripcion' => 'Arruga Longitudinal En La Base De La Válvula; A Los Lados Y Arriba',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            59 => 
            array (
                'id' => 60,
                'codigo' => '911C',
                'descripcion' => 'Arruga Longitudinal En La Base De La Válvula; A Los Lados Y Debajo.',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            60 => 
            array (
                'id' => 61,
                'codigo' => '911D',
                'descripcion' => 'Arruga Longitudinal En La Base De La Válvula; Arriba Y Perpendicular',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            61 => 
            array (
                'id' => 62,
                'codigo' => '911E',
                'descripcion' => 'Arruga Longitudinal En La Base De La Válvula; Debajo Y Perpendicular',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            62 => 
            array (
                'id' => 63,
                'codigo' => '921A',
                'descripcion' => 'Debilidad/Cuerpo; En Hombro',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            63 => 
            array (
                'id' => 64,
                'codigo' => '921B',
                'descripcion' => 'Debilidad/Cuerpo; Entre Hombro Y Base',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            64 => 
            array (
                'id' => 65,
                'codigo' => '921C',
                'descripcion' => 'Debilidad/Cuerpo; Entre Hombro Y Corona',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            65 => 
            array (
                'id' => 66,
                'codigo' => '921D',
                'descripcion' => 'Debilidad/Cuerpo; En La Corona, Doblez Del Tubo',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            66 => 
            array (
                'id' => 67,
                'codigo' => '922A',
                'descripcion' => 'Debilidad En El Empate - Hombro Del Tubo',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
            67 => 
            array (
                'id' => 68,
                'codigo' => '922B',
                'descripcion' => 'Debilidad En El Empate - Corona Del Tubo',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2021-10-26 17:44:22',
                'updated_at' => '2021-10-26 17:44:22',
            ),
        ));
        
        
    }
}