<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class InformacionProductoTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('informacion_producto')->delete();
        
        \DB::table('informacion_producto')->insert(array (
            0 => 
            array (
                'id' => 1,
                'idReclamo' => 1,
                'idProducto' => 1,
                'idPais' => NULL,
                'idMarcaCaucho' => 1,
                'idModeloCaucho' => 1,
                'idMedidaCaucho' => 2,
                'idDisenoBanda' => 1,
                'idProfundidad' => 15,
                'dotSerial' => '123',
                'profundidad' => '23',
                'boleta' => '5027743',
                'tipoRenovado' => 1,
                'serial' => '23344',
                'loteBanda' => NULL,
                'loteVulcanizacion' => NULL,
                'loteProducto' => NULL,
                'valvula' => NULL,
                'fechaRecepcion' => '2005-09-15 01:18:58',
                'activo' => 1,
                'estado' => 1,
                'idUsuario' => 27,
                'created_at' => '2022-01-24 10:33:27',
                'updated_at' => '2022-01-24 10:33:27',
            ),
            1 => 
            array (
                'id' => 2,
                'idReclamo' => 2,
                'idProducto' => 1,
                'idPais' => NULL,
                'idMarcaCaucho' => 1,
                'idModeloCaucho' => 1,
                'idMedidaCaucho' => 5,
                'idDisenoBanda' => 2,
                'idProfundidad' => 11,
                'dotSerial' => '1718',
                'profundidad' => '12',
                'boleta' => '4987343',
                'tipoRenovado' => 1,
                'serial' => 'CV0004684/1921',
                'loteBanda' => NULL,
                'loteVulcanizacion' => NULL,
                'loteProducto' => NULL,
                'valvula' => NULL,
                'fechaRecepcion' => '2005-11-03 00:28:46',
                'activo' => 1,
                'estado' => 1,
                'idUsuario' => 27,
                'created_at' => '2022-01-24 11:46:24',
                'updated_at' => '2022-01-24 11:46:24',
            ),
            2 => 
            array (
                'id' => 3,
                'idReclamo' => 3,
                'idProducto' => 1,
                'idPais' => NULL,
                'idMarcaCaucho' => 18,
                'idModeloCaucho' => NULL,
                'idMedidaCaucho' => 1,
                'idDisenoBanda' => 14,
                'idProfundidad' => 1,
                'dotSerial' => '3717',
                'profundidad' => '10',
                'boleta' => '4987313',
                'tipoRenovado' => 1,
                'serial' => 'CV0001733',
                'loteBanda' => NULL,
                'loteVulcanizacion' => NULL,
                'loteProducto' => NULL,
                'valvula' => NULL,
                'fechaRecepcion' => '2005-11-18 07:16:13',
                'activo' => 1,
                'estado' => 1,
                'idUsuario' => 27,
                'created_at' => '2022-01-24 12:08:24',
                'updated_at' => '2022-01-24 12:08:24',
            ),
            3 => 
            array (
                'id' => 4,
                'idReclamo' => 1,
                'idProducto' => 1,
                'idPais' => NULL,
                'idMarcaCaucho' => 1,
                'idModeloCaucho' => 1,
                'idMedidaCaucho' => 2,
                'idDisenoBanda' => 1,
                'idProfundidad' => 15,
                'dotSerial' => '123',
                'profundidad' => '1',
                'boleta' => NULL,
                'tipoRenovado' => 0,
                'serial' => '23344',
                'loteBanda' => NULL,
                'loteVulcanizacion' => NULL,
                'loteProducto' => NULL,
                'valvula' => NULL,
                'fechaRecepcion' => NULL,
                'activo' => 1,
                'estado' => 1,
                'idUsuario' => 1,
                'created_at' => '2022-01-24 12:09:48',
                'updated_at' => '2022-01-24 12:09:48',
            ),
            4 => 
            array (
                'id' => 5,
                'idReclamo' => 4,
                'idProducto' => 1,
                'idPais' => NULL,
                'idMarcaCaucho' => 1,
                'idModeloCaucho' => 4,
                'idMedidaCaucho' => 81,
                'idDisenoBanda' => 14,
                'idProfundidad' => 1,
                'dotSerial' => '1718',
                'profundidad' => '10',
                'boleta' => '5094692',
                'tipoRenovado' => 1,
                'serial' => 'AZ0000110',
                'loteBanda' => NULL,
                'loteVulcanizacion' => NULL,
                'loteProducto' => NULL,
                'valvula' => NULL,
                'fechaRecepcion' => '2005-12-17 20:48:31',
                'activo' => 1,
                'estado' => 1,
                'idUsuario' => 27,
                'created_at' => '2022-01-24 12:50:58',
                'updated_at' => '2022-01-24 12:50:58',
            ),
            5 => 
            array (
                'id' => 6,
                'idReclamo' => 4,
                'idProducto' => 1,
                'idPais' => NULL,
                'idMarcaCaucho' => 1,
                'idModeloCaucho' => 4,
                'idMedidaCaucho' => 81,
                'idDisenoBanda' => 14,
                'idProfundidad' => 1,
                'dotSerial' => '1718',
                'profundidad' => '9',
                'boleta' => NULL,
                'tipoRenovado' => 0,
                'serial' => 'AZ0000110',
                'loteBanda' => NULL,
                'loteVulcanizacion' => NULL,
                'loteProducto' => NULL,
                'valvula' => NULL,
                'fechaRecepcion' => NULL,
                'activo' => 1,
                'estado' => 1,
                'idUsuario' => 1,
                'created_at' => '2022-01-24 13:05:28',
                'updated_at' => '2022-01-24 13:05:28',
            ),
            6 => 
            array (
                'id' => 7,
                'idReclamo' => 5,
                'idProducto' => 1,
                'idPais' => NULL,
                'idMarcaCaucho' => 38,
                'idModeloCaucho' => 153,
                'idMedidaCaucho' => 10,
                'idDisenoBanda' => 14,
                'idProfundidad' => 1,
                'dotSerial' => '1218',
                'profundidad' => '10',
                'boleta' => '5094658',
                'tipoRenovado' => 1,
                'serial' => 'CV0002882',
                'loteBanda' => NULL,
                'loteVulcanizacion' => NULL,
                'loteProducto' => NULL,
                'valvula' => NULL,
                'fechaRecepcion' => '2006-04-10 01:18:44',
                'activo' => 1,
                'estado' => 1,
                'idUsuario' => 27,
                'created_at' => '2022-01-24 15:35:25',
                'updated_at' => '2022-01-24 15:35:25',
            ),
            7 => 
            array (
                'id' => 8,
                'idReclamo' => 6,
                'idProducto' => 4,
                'idPais' => NULL,
                'idMarcaCaucho' => NULL,
                'idModeloCaucho' => NULL,
                'idMedidaCaucho' => 2,
                'idDisenoBanda' => 1,
                'idProfundidad' => 15,
                'dotSerial' => NULL,
                'profundidad' => '20',
                'boleta' => NULL,
                'tipoRenovado' => 0,
                'serial' => NULL,
                'loteBanda' => NULL,
                'loteVulcanizacion' => NULL,
                'loteProducto' => NULL,
                'valvula' => NULL,
                'fechaRecepcion' => '2006-06-23 15:15:57',
                'activo' => 1,
                'estado' => 1,
                'idUsuario' => 1,
                'created_at' => '2022-01-24 17:19:47',
                'updated_at' => '2022-01-24 17:19:47',
            ),
            8 => 
            array (
                'id' => 9,
                'idReclamo' => 7,
                'idProducto' => 4,
                'idPais' => NULL,
                'idMarcaCaucho' => NULL,
                'idModeloCaucho' => NULL,
                'idMedidaCaucho' => 2,
                'idDisenoBanda' => 1,
                'idProfundidad' => 15,
                'dotSerial' => NULL,
                'profundidad' => '23',
                'boleta' => NULL,
                'tipoRenovado' => 0,
                'serial' => NULL,
                'loteBanda' => NULL,
                'loteVulcanizacion' => NULL,
                'loteProducto' => NULL,
                'valvula' => NULL,
                'fechaRecepcion' => '2006-06-28 10:44:18',
                'activo' => 1,
                'estado' => 1,
                'idUsuario' => 1,
                'created_at' => '2022-01-24 17:26:35',
                'updated_at' => '2022-01-24 17:26:35',
            ),
            9 => 
            array (
                'id' => 10,
                'idReclamo' => 23,
                'idProducto' => 2,
                'idPais' => 0,
                'idMarcaCaucho' => 1,
                'idModeloCaucho' => 3,
                'idMedidaCaucho' => 7,
                'idDisenoBanda' => 4,
                'idProfundidad' => 13,
                'dotSerial' => '123456',
                'profundidad' => '12',
                'boleta' => '',
                'tipoRenovado' => 1,
                'serial' => '',
                'loteBanda' => '',
                'loteVulcanizacion' => '',
                'loteProducto' => '',
                'valvula' => '',
                'fechaRecepcion' => '2006-08-27 20:00:00',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}