<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PaisTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pais')->delete();
        
        \DB::table('pais')->insert(array (
            0 => 
            array (
                'id' => 1,
                'iso2' => 'AL',
                'descripcion' => 'Albania',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            1 => 
            array (
                'id' => 2,
                'iso2' => 'DE',
                'descripcion' => 'Alemania',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            2 => 
            array (
                'id' => 3,
                'iso2' => 'AD',
                'descripcion' => 'Andorra',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            3 => 
            array (
                'id' => 4,
                'iso2' => 'AO',
                'descripcion' => 'Angola',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            4 => 
            array (
                'id' => 5,
                'iso2' => 'AG',
                'descripcion' => 'Antigua y Barbuda',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            5 => 
            array (
                'id' => 6,
                'iso2' => 'SA',
                'descripcion' => 'Arabia Saudita',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            6 => 
            array (
                'id' => 7,
                'iso2' => 'DZ',
                'descripcion' => 'Argelia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            7 => 
            array (
                'id' => 8,
                'iso2' => 'AR',
                'descripcion' => 'Argentina',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            8 => 
            array (
                'id' => 9,
                'iso2' => 'AM',
                'descripcion' => 'Armenia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            9 => 
            array (
                'id' => 10,
                'iso2' => 'AU',
                'descripcion' => 'Australia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            10 => 
            array (
                'id' => 11,
                'iso2' => 'AT',
                'descripcion' => 'Austria',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            11 => 
            array (
                'id' => 12,
                'iso2' => 'AZ',
                'descripcion' => 'Azerbaiyán',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            12 => 
            array (
                'id' => 13,
                'iso2' => 'BS',
                'descripcion' => 'Bahamas',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            13 => 
            array (
                'id' => 14,
                'iso2' => 'BH',
                'descripcion' => 'Bahrein',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            14 => 
            array (
                'id' => 15,
                'iso2' => 'BD',
                'descripcion' => 'Bangladesh',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            15 => 
            array (
                'id' => 16,
                'iso2' => 'BB',
                'descripcion' => 'Barbados',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            16 => 
            array (
                'id' => 17,
                'iso2' => 'BY',
                'descripcion' => 'Belarús',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            17 => 
            array (
                'id' => 18,
                'iso2' => 'BZ',
                'descripcion' => 'Belice',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            18 => 
            array (
                'id' => 19,
                'iso2' => 'BJ',
                'descripcion' => 'Benin',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            19 => 
            array (
                'id' => 20,
                'iso2' => 'BT',
                'descripcion' => 'Bhután',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            20 => 
            array (
                'id' => 21,
                'iso2' => 'BO',
                'descripcion' => 'Bolivia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            21 => 
            array (
                'id' => 22,
                'iso2' => 'BA',
                'descripcion' => 'Bosnia y Herzegovina',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            22 => 
            array (
                'id' => 23,
                'iso2' => 'BW',
                'descripcion' => 'Botswana',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            23 => 
            array (
                'id' => 24,
                'iso2' => 'BR',
                'descripcion' => 'Brasil',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            24 => 
            array (
                'id' => 25,
                'iso2' => 'BN',
                'descripcion' => 'Brunei Darussalam',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            25 => 
            array (
                'id' => 26,
                'iso2' => 'BG',
                'descripcion' => 'Bulgaria',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            26 => 
            array (
                'id' => 27,
                'iso2' => 'BF',
                'descripcion' => 'Burkina Faso',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            27 => 
            array (
                'id' => 28,
                'iso2' => 'BI',
                'descripcion' => 'Burundi',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            28 => 
            array (
                'id' => 29,
                'iso2' => 'BE',
                'descripcion' => 'Bélgica',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            29 => 
            array (
                'id' => 30,
                'iso2' => 'CV',
                'descripcion' => 'Cabo Verde',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            30 => 
            array (
                'id' => 31,
                'iso2' => 'KH',
                'descripcion' => 'Camboya',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            31 => 
            array (
                'id' => 32,
                'iso2' => 'CM',
                'descripcion' => 'Camerún',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            32 => 
            array (
                'id' => 33,
                'iso2' => 'CA',
                'descripcion' => 'Canadá',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            33 => 
            array (
                'id' => 34,
                'iso2' => 'TD',
                'descripcion' => 'Chad',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            34 => 
            array (
                'id' => 35,
                'iso2' => 'CZ',
                'descripcion' => 'Chequia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            35 => 
            array (
                'id' => 36,
                'iso2' => 'CL',
                'descripcion' => 'Chile',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            36 => 
            array (
                'id' => 37,
                'iso2' => 'CN',
                'descripcion' => 'China',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            37 => 
            array (
                'id' => 38,
                'iso2' => 'CY',
                'descripcion' => 'Chipre',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            38 => 
            array (
                'id' => 39,
                'iso2' => 'CO',
                'descripcion' => 'Colombia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            39 => 
            array (
                'id' => 40,
                'iso2' => 'KM',
                'descripcion' => 'Comoras',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            40 => 
            array (
                'id' => 41,
                'iso2' => 'CG',
                'descripcion' => 'Congo',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            41 => 
            array (
                'id' => 42,
                'iso2' => 'CR',
                'descripcion' => 'Costa Rica',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            42 => 
            array (
                'id' => 43,
                'iso2' => 'HR',
                'descripcion' => 'Croacia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            43 => 
            array (
                'id' => 44,
                'iso2' => 'CU',
                'descripcion' => 'Cuba',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            44 => 
            array (
                'id' => 45,
                'iso2' => 'CI',
                'descripcion' => 'Costa de Marfíl',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            45 => 
            array (
                'id' => 46,
                'iso2' => 'DK',
                'descripcion' => 'Dinamarca',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            46 => 
            array (
                'id' => 47,
                'iso2' => 'DJ',
                'descripcion' => 'Djibouti',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            47 => 
            array (
                'id' => 48,
                'iso2' => 'DM',
                'descripcion' => 'Dominica',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            48 => 
            array (
                'id' => 49,
                'iso2' => 'EC',
                'descripcion' => 'Ecuador',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            49 => 
            array (
                'id' => 50,
                'iso2' => 'EG',
                'descripcion' => 'Egipto',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            50 => 
            array (
                'id' => 51,
                'iso2' => 'SV',
                'descripcion' => 'El Salvador',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            51 => 
            array (
                'id' => 52,
                'iso2' => 'AE',
                'descripcion' => 'Emiratos Árabes Unidos',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            52 => 
            array (
                'id' => 53,
                'iso2' => 'ER',
                'descripcion' => 'Eritrea',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            53 => 
            array (
                'id' => 54,
                'iso2' => 'SK',
                'descripcion' => 'Eslovaquia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            54 => 
            array (
                'id' => 55,
                'iso2' => 'SI',
                'descripcion' => 'Eslovenia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            55 => 
            array (
                'id' => 56,
                'iso2' => 'ES',
                'descripcion' => 'España',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            56 => 
            array (
                'id' => 57,
                'iso2' => 'US',
                'descripcion' => 'Estados Unidos de América',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            57 => 
            array (
                'id' => 58,
                'iso2' => 'EE',
                'descripcion' => 'Estonia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            58 => 
            array (
                'id' => 59,
                'iso2' => 'SZ',
                'descripcion' => 'Eswatini',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            59 => 
            array (
                'id' => 60,
                'iso2' => 'ET',
                'descripcion' => 'Etiopía',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            60 => 
            array (
                'id' => 61,
                'iso2' => 'RU',
                'descripcion' => 'Federación de Rusia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            61 => 
            array (
                'id' => 62,
                'iso2' => 'FJ',
                'descripcion' => 'Fiji',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            62 => 
            array (
                'id' => 63,
                'iso2' => 'PH',
                'descripcion' => 'Filipinas',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            63 => 
            array (
                'id' => 64,
                'iso2' => 'FI',
                'descripcion' => 'Finlandia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            64 => 
            array (
                'id' => 65,
                'iso2' => 'FR',
                'descripcion' => 'Francia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            65 => 
            array (
                'id' => 66,
                'iso2' => 'GA',
                'descripcion' => 'Gabón',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            66 => 
            array (
                'id' => 67,
                'iso2' => 'GM',
                'descripcion' => 'Gambia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            67 => 
            array (
                'id' => 68,
                'iso2' => 'GE',
                'descripcion' => 'Georgia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            68 => 
            array (
                'id' => 69,
                'iso2' => 'GH',
                'descripcion' => 'Ghana',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            69 => 
            array (
                'id' => 70,
                'iso2' => 'GD',
                'descripcion' => 'Granada',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            70 => 
            array (
                'id' => 71,
                'iso2' => 'GR',
                'descripcion' => 'Grecia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            71 => 
            array (
                'id' => 72,
                'iso2' => 'GT',
                'descripcion' => 'Guatemala',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            72 => 
            array (
                'id' => 73,
                'iso2' => 'GN',
                'descripcion' => 'Guinea',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            73 => 
            array (
                'id' => 74,
                'iso2' => 'GQ',
                'descripcion' => 'Guinea Ecuatorial',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            74 => 
            array (
                'id' => 75,
                'iso2' => 'GW',
                'descripcion' => 'Guinea-Bissau',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            75 => 
            array (
                'id' => 76,
                'iso2' => 'GY',
                'descripcion' => 'Guyana',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            76 => 
            array (
                'id' => 77,
                'iso2' => 'HT',
                'descripcion' => 'Haití',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            77 => 
            array (
                'id' => 78,
                'iso2' => 'HN',
                'descripcion' => 'Honduras',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            78 => 
            array (
                'id' => 79,
                'iso2' => 'HU',
                'descripcion' => 'Hungría',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            79 => 
            array (
                'id' => 80,
                'iso2' => 'IN',
                'descripcion' => 'India',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            80 => 
            array (
                'id' => 81,
                'iso2' => 'ID',
                'descripcion' => 'Indonesia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            81 => 
            array (
                'id' => 82,
                'iso2' => 'IQ',
                'descripcion' => 'Iraq',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            82 => 
            array (
                'id' => 83,
                'iso2' => 'IE',
                'descripcion' => 'Irlanda',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            83 => 
            array (
                'id' => 84,
                'iso2' => 'IR',
                'descripcion' => 'Irán',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            84 => 
            array (
                'id' => 85,
                'iso2' => 'IS',
                'descripcion' => 'Islandia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            85 => 
            array (
                'id' => 86,
                'iso2' => 'CK',
                'descripcion' => 'Islas Cook',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            86 => 
            array (
                'id' => 87,
                'iso2' => 'FO',
                'descripcion' => 'Islas Feroe',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            87 => 
            array (
                'id' => 88,
                'iso2' => 'MH',
                'descripcion' => 'Islas Marshall',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            88 => 
            array (
                'id' => 89,
                'iso2' => 'SB',
                'descripcion' => 'Islas Salomón',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            89 => 
            array (
                'id' => 90,
                'iso2' => 'IL',
                'descripcion' => 'Israel',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            90 => 
            array (
                'id' => 91,
                'iso2' => 'IT',
                'descripcion' => 'Italia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            91 => 
            array (
                'id' => 92,
                'iso2' => 'JM',
                'descripcion' => 'Jamaica',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            92 => 
            array (
                'id' => 93,
                'iso2' => 'JP',
                'descripcion' => 'Japón',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            93 => 
            array (
                'id' => 94,
                'iso2' => 'JO',
                'descripcion' => 'Jordania',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            94 => 
            array (
                'id' => 95,
                'iso2' => 'KZ',
                'descripcion' => 'Kazajstán',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            95 => 
            array (
                'id' => 96,
                'iso2' => 'KE',
                'descripcion' => 'Kenya',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            96 => 
            array (
                'id' => 97,
                'iso2' => 'KG',
                'descripcion' => 'Kirguistán',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            97 => 
            array (
                'id' => 98,
                'iso2' => 'KI',
                'descripcion' => 'Kiribati',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            98 => 
            array (
                'id' => 99,
                'iso2' => 'KW',
                'descripcion' => 'Kuwait',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            99 => 
            array (
                'id' => 100,
                'iso2' => 'LS',
                'descripcion' => 'Lesotho',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            100 => 
            array (
                'id' => 101,
                'iso2' => 'LV',
                'descripcion' => 'Letonia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            101 => 
            array (
                'id' => 102,
                'iso2' => 'LR',
                'descripcion' => 'Liberia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            102 => 
            array (
                'id' => 103,
                'iso2' => 'LY',
                'descripcion' => 'Libia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            103 => 
            array (
                'id' => 104,
                'iso2' => 'LT',
                'descripcion' => 'Lituania',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            104 => 
            array (
                'id' => 105,
                'iso2' => 'LU',
                'descripcion' => 'Luxemburgo',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            105 => 
            array (
                'id' => 106,
                'iso2' => 'LB',
                'descripcion' => 'Líbano',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            106 => 
            array (
                'id' => 107,
                'iso2' => 'MK',
                'descripcion' => 'Macedonia del Norte',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            107 => 
            array (
                'id' => 108,
                'iso2' => 'MG',
                'descripcion' => 'Madagascar',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            108 => 
            array (
                'id' => 109,
                'iso2' => 'MY',
                'descripcion' => 'Malasia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            109 => 
            array (
                'id' => 110,
                'iso2' => 'MW',
                'descripcion' => 'Malawi',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            110 => 
            array (
                'id' => 111,
                'iso2' => 'MV',
                'descripcion' => 'Maldivas',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            111 => 
            array (
                'id' => 112,
                'iso2' => 'MT',
                'descripcion' => 'Malta',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            112 => 
            array (
                'id' => 113,
                'iso2' => 'ML',
                'descripcion' => 'Malí',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            113 => 
            array (
                'id' => 114,
                'iso2' => 'MA',
                'descripcion' => 'Marruecos',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            114 => 
            array (
                'id' => 115,
                'iso2' => 'MU',
                'descripcion' => 'Mauricio',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            115 => 
            array (
                'id' => 116,
                'iso2' => 'MR',
                'descripcion' => 'Mauritania',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            116 => 
            array (
                'id' => 117,
                'iso2' => 'FM',
                'descripcion' => 'Micronesia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            117 => 
            array (
                'id' => 118,
                'iso2' => 'MN',
                'descripcion' => 'Mongolia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            118 => 
            array (
                'id' => 119,
                'iso2' => 'ME',
                'descripcion' => 'Montenegro',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            119 => 
            array (
                'id' => 120,
                'iso2' => 'MZ',
                'descripcion' => 'Mozambique',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            120 => 
            array (
                'id' => 121,
                'iso2' => 'MM',
                'descripcion' => 'Myanmar',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            121 => 
            array (
                'id' => 122,
                'iso2' => 'MX',
                'descripcion' => 'México',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            122 => 
            array (
                'id' => 123,
                'iso2' => 'MC',
                'descripcion' => 'Mónaco',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            123 => 
            array (
                'id' => 124,
                'iso2' => 'NA',
                'descripcion' => 'Namibia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            124 => 
            array (
                'id' => 125,
                'iso2' => 'NR',
                'descripcion' => 'Nauru',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            125 => 
            array (
                'id' => 126,
                'iso2' => 'NP',
                'descripcion' => 'Nepal',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            126 => 
            array (
                'id' => 127,
                'iso2' => 'NI',
                'descripcion' => 'Nicaragua',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            127 => 
            array (
                'id' => 128,
                'iso2' => 'NG',
                'descripcion' => 'Nigeria',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            128 => 
            array (
                'id' => 129,
                'iso2' => 'NU',
                'descripcion' => 'Niue',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            129 => 
            array (
                'id' => 130,
                'iso2' => 'NO',
                'descripcion' => 'Noruega',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            130 => 
            array (
                'id' => 131,
                'iso2' => 'NZ',
                'descripcion' => 'Nueva Zelandia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            131 => 
            array (
                'id' => 132,
                'iso2' => 'NE',
                'descripcion' => 'Níger',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            132 => 
            array (
                'id' => 133,
                'iso2' => 'OM',
                'descripcion' => 'Omán',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            133 => 
            array (
                'id' => 134,
                'iso2' => 'PK',
                'descripcion' => 'Pakistán',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            134 => 
            array (
                'id' => 135,
                'iso2' => 'PW',
                'descripcion' => 'Palau',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            135 => 
            array (
                'id' => 136,
                'iso2' => 'PA',
                'descripcion' => 'Panamá',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            136 => 
            array (
                'id' => 137,
                'iso2' => 'PG',
                'descripcion' => 'Papua Nueva Guinea',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            137 => 
            array (
                'id' => 138,
                'iso2' => 'PY',
                'descripcion' => 'Paraguay',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            138 => 
            array (
                'id' => 139,
                'iso2' => 'NL',
                'descripcion' => 'Países Bajos',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            139 => 
            array (
                'id' => 140,
                'iso2' => 'PE',
                'descripcion' => 'Perú',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            140 => 
            array (
                'id' => 141,
                'iso2' => 'PL',
                'descripcion' => 'Polonia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            141 => 
            array (
                'id' => 142,
                'iso2' => 'PT',
                'descripcion' => 'Portugal',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            142 => 
            array (
                'id' => 143,
                'iso2' => 'QA',
                'descripcion' => 'Qatar',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            143 => 
            array (
                'id' => 144,
                'iso2' => 'CF',
                'descripcion' => 'República Centroafricana',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            144 => 
            array (
                'id' => 145,
                'iso2' => 'GB',
                'descripcion' => 'Reino Unido de Gran Bretaña e Irlanda del Norte',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            145 => 
            array (
                'id' => 147,
                'iso2' => 'LA',
                'descripcion' => 'República Democrática Popular Lao',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            146 => 
            array (
                'id' => 148,
                'iso2' => 'CD',
                'descripcion' => 'República Democrática del Congo',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            147 => 
            array (
                'id' => 149,
                'iso2' => 'DO',
                'descripcion' => 'República Dominicana',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            148 => 
            array (
                'id' => 150,
                'iso2' => 'KP',
                'descripcion' => 'República Popular Democrática de Corea',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            149 => 
            array (
                'id' => 151,
                'iso2' => 'TZ',
                'descripcion' => 'República Unida de Tanzanía',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            150 => 
            array (
                'id' => 152,
                'iso2' => 'KR',
                'descripcion' => 'República de Corea',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            151 => 
            array (
                'id' => 153,
                'iso2' => 'MD',
                'descripcion' => 'República de Moldova',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            152 => 
            array (
                'id' => 154,
                'iso2' => 'SY',
                'descripcion' => 'República Árabe Siria',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            153 => 
            array (
                'id' => 155,
                'iso2' => 'RO',
                'descripcion' => 'Rumania',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            154 => 
            array (
                'id' => 156,
                'iso2' => 'RW',
                'descripcion' => 'Rwanda',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            155 => 
            array (
                'id' => 157,
                'iso2' => 'KN',
                'descripcion' => 'Saint Kitts y Nevis',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            156 => 
            array (
                'id' => 158,
                'iso2' => 'WS',
                'descripcion' => 'Samoa',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            157 => 
            array (
                'id' => 159,
                'iso2' => 'SM',
                'descripcion' => 'San Marino',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            158 => 
            array (
                'id' => 160,
                'iso2' => 'VC',
                'descripcion' => 'San Vicente y las Granadinas',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            159 => 
            array (
                'id' => 161,
                'iso2' => 'LC',
                'descripcion' => 'Santa Lucía',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            160 => 
            array (
                'id' => 162,
                'iso2' => 'ST',
                'descripcion' => 'Santo Tomé y Príncipe',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            161 => 
            array (
                'id' => 163,
                'iso2' => 'SN',
                'descripcion' => 'Senegal',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            162 => 
            array (
                'id' => 164,
                'iso2' => 'RS',
                'descripcion' => 'Serbia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            163 => 
            array (
                'id' => 165,
                'iso2' => 'SC',
                'descripcion' => 'Seychelles',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            164 => 
            array (
                'id' => 166,
                'iso2' => 'SL',
                'descripcion' => 'Sierra Leona',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            165 => 
            array (
                'id' => 167,
                'iso2' => 'SG',
                'descripcion' => 'Singapur',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            166 => 
            array (
                'id' => 168,
                'iso2' => 'SO',
                'descripcion' => 'Somalia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            167 => 
            array (
                'id' => 169,
                'iso2' => 'LK',
                'descripcion' => 'Sri Lanka',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            168 => 
            array (
                'id' => 170,
                'iso2' => 'ZA',
                'descripcion' => 'Sudáfrica',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            169 => 
            array (
                'id' => 171,
                'iso2' => 'SD',
                'descripcion' => 'Sudán',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            170 => 
            array (
                'id' => 172,
                'iso2' => 'SS',
                'descripcion' => 'Sudán del Sur',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            171 => 
            array (
                'id' => 173,
                'iso2' => 'SE',
                'descripcion' => 'Suecia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            172 => 
            array (
                'id' => 174,
                'iso2' => 'CH',
                'descripcion' => 'Suiza',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            173 => 
            array (
                'id' => 175,
                'iso2' => 'SR',
                'descripcion' => 'Suriname',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            174 => 
            array (
                'id' => 176,
                'iso2' => 'TH',
                'descripcion' => 'Tailandia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            175 => 
            array (
                'id' => 177,
                'iso2' => 'TJ',
                'descripcion' => 'Tayikistán',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            176 => 
            array (
                'id' => 178,
                'iso2' => 'TL',
                'descripcion' => 'Timor-Leste',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            177 => 
            array (
                'id' => 179,
                'iso2' => 'TG',
                'descripcion' => 'Togo',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            178 => 
            array (
                'id' => 180,
                'iso2' => 'TK',
                'descripcion' => 'Tokelau',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            179 => 
            array (
                'id' => 181,
                'iso2' => 'TO',
                'descripcion' => 'Tonga',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            180 => 
            array (
                'id' => 182,
                'iso2' => 'TT',
                'descripcion' => 'Trinidad y Tabago',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            181 => 
            array (
                'id' => 183,
                'iso2' => 'TM',
                'descripcion' => 'Turkmenistán',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            182 => 
            array (
                'id' => 184,
                'iso2' => 'TR',
                'descripcion' => 'Turquía',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            183 => 
            array (
                'id' => 185,
                'iso2' => 'TV',
                'descripcion' => 'Tuvalu',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            184 => 
            array (
                'id' => 186,
                'iso2' => 'TN',
                'descripcion' => 'Túnez',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            185 => 
            array (
                'id' => 187,
                'iso2' => 'UA',
                'descripcion' => 'Ucrania',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            186 => 
            array (
                'id' => 188,
                'iso2' => 'UG',
                'descripcion' => 'Uganda',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            187 => 
            array (
                'id' => 189,
                'iso2' => 'UY',
                'descripcion' => 'Uruguay',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            188 => 
            array (
                'id' => 190,
                'iso2' => 'UZ',
                'descripcion' => 'Uzbekistán',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            189 => 
            array (
                'id' => 191,
                'iso2' => 'VU',
                'descripcion' => 'Vanuatu',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            190 => 
            array (
                'id' => 192,
                'iso2' => 'VE',
                'descripcion' => 'Venezuela',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            191 => 
            array (
                'id' => 193,
                'iso2' => 'VN',
                'descripcion' => 'Viet Nam',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            192 => 
            array (
                'id' => 194,
                'iso2' => 'YE',
                'descripcion' => 'Yemen',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            193 => 
            array (
                'id' => 195,
                'iso2' => 'ZM',
                'descripcion' => 'Zambia',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
            194 => 
            array (
                'id' => 196,
                'iso2' => 'ZW',
                'descripcion' => 'Zimbabwe',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => '1',
                'created_at' => '2021-10-26 17:44:24',
                'updated_at' => '2021-10-26 17:44:24',
            ),
        ));
        
        
    }
}