<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RechazoTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('rechazo')->delete();
        
        \DB::table('rechazo')->insert(array (
            0 => 
            array (
                'id' => 1,
                'codigo' => 'G24',
                'idZona' => 1,
                'descripcion' => 'Carcasa no apta para renovar - Falla en ',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            1 => 
            array (
                'id' => 2,
                'codigo' => 'G25',
                'idZona' => 1,
                'descripcion' => 'Asignación de diseño incorrecto de banda',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            2 => 
            array (
                'id' => 3,
                'codigo' => 'G26',
                'idZona' => 1,
                'descripcion' => 'Carcasa vieja renovada',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            3 => 
            array (
                'id' => 4,
                'codigo' => 'G52',
                'idZona' => 1,
                'descripcion' => 'Carcasa fuera del límite de garantía',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            4 => 
            array (
                'id' => 5,
                'codigo' => 'G53',
                'idZona' => 1,
                'descripcion' => 'Separación de los cables de acero de la ',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            5 => 
            array (
                'id' => 6,
                'codigo' => 'G54',
                'idZona' => 1,
                'descripcion' => 'Reparación no adecuada',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            6 => 
            array (
                'id' => 7,
                'codigo' => 'G60',
                'idZona' => 1,
                'descripcion' => 'Goma agrietada o envejecida',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            7 => 
            array (
                'id' => 8,
                'codigo' => 'G61',
                'idZona' => 1,
                'descripcion' => 'Daño por contacto con sustancia química',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            8 => 
            array (
                'id' => 9,
                'codigo' => 'G62',
                'idZona' => 1,
                'descripcion' => 'Quiebre o daño del parche',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            9 => 
            array (
                'id' => 10,
                'codigo' => 'G27',
                'idZona' => 2,
                'descripcion' => 'Caucho con desbalanceo',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            10 => 
            array (
                'id' => 11,
                'codigo' => 'G28',
                'idZona' => 2,
                'descripcion' => 'Grieta en el inner liner',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            11 => 
            array (
                'id' => 12,
                'codigo' => 'G29',
                'idZona' => 2,
                'descripcion' => 'Caucho con material extraño',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            12 => 
            array (
                'id' => 13,
                'codigo' => 'G30',
                'idZona' => 2,
                'descripcion' => 'Caucho con separación de la banda de rod',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            13 => 
            array (
                'id' => 14,
                'codigo' => 'G31',
                'idZona' => 2,
                'descripcion' => 'Caucho con problema de vulcanización',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            14 => 
            array (
                'id' => 15,
                'codigo' => 'G03',
                'idZona' => 3,
                'descripcion' => 'Desprendimiento de la banda de rodamiento',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            15 => 
            array (
                'id' => 16,
                'codigo' => 'G04',
                'idZona' => 3,
                'descripcion' => 'Falta de adhesión de cojín',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            16 => 
            array (
                'id' => 17,
                'codigo' => 'G05',
                'idZona' => 3,
                'descripcion' => 'Porosidad en el cojín',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            17 => 
            array (
                'id' => 18,
                'codigo' => 'G06',
                'idZona' => 3,
                'descripcion' => 'Porosidad de la banda preestampada',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            18 => 
            array (
                'id' => 19,
                'codigo' => 'G08',
                'idZona' => 3,
                'descripcion' => 'Contaminación en el cojín',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            19 => 
            array (
                'id' => 20,
                'codigo' => 'G09',
                'idZona' => 3,
                'descripcion' => 'Banda sin textura',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            20 => 
            array (
                'id' => 21,
                'codigo' => 'G10',
                'idZona' => 3,
                'descripcion' => 'Empate abierto - Banda preestampada',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            21 => 
            array (
                'id' => 22,
                'codigo' => 'G11',
                'idZona' => 3,
                'descripcion' => 'Empate abierto - Camelback',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            22 => 
            array (
                'id' => 23,
                'codigo' => 'G12',
                'idZona' => 3,
                'descripcion' => 'Largo de empate fuera de especificación',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            23 => 
            array (
                'id' => 24,
                'codigo' => 'G13',
                'idZona' => 3,
                'descripcion' => 'Arruga en la banda de rodamiento',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            24 => 
            array (
                'id' => 25,
                'codigo' => 'G14',
                'idZona' => 3,
                'descripcion' => 'Ancho incorrecto de banda',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            25 => 
            array (
                'id' => 26,
                'codigo' => 'G15',
                'idZona' => 3,
                'descripcion' => 'Banda descentrada',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            26 => 
            array (
                'id' => 27,
                'codigo' => 'G16',
                'idZona' => 3,
                'descripcion' => 'Ampollas en los tacos de la banda',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            27 => 
            array (
                'id' => 28,
                'codigo' => 'G32',
                'idZona' => 3,
                'descripcion' => 'Filtración de aire por mala reparación',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            28 => 
            array (
                'id' => 29,
                'codigo' => 'G33',
                'idZona' => 3,
                'descripcion' => 'Desprendimiento de la banda de rodamient',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            29 => 
            array (
                'id' => 30,
                'codigo' => 'G64',
                'idZona' => 3,
                'descripcion' => 'Separación/arrancamiento de goma en la c',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            30 => 
            array (
                'id' => 31,
                'codigo' => 'G07',
                'idZona' => 4,
            'descripcion' => 'Porosidad en la banda (camelback)',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            31 => 
            array (
                'id' => 32,
                'codigo' => 'G17',
                'idZona' => 4,
                'descripcion' => 'Exceso de relleno en el hombro o la coro',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            32 => 
            array (
                'id' => 33,
                'codigo' => 'G38',
                'idZona' => 4,
                'descripcion' => 'Oxidación en la corona',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            33 => 
            array (
                'id' => 34,
                'codigo' => 'G01',
                'idZona' => 5,
                'descripcion' => 'Filtración de aire por mala reparación',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            34 => 
            array (
                'id' => 35,
                'codigo' => 'G02',
                'idZona' => 5,
                'descripcion' => 'Filtración de aire por parche CVC',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            35 => 
            array (
                'id' => 36,
                'codigo' => 'G34',
                'idZona' => 5,
            'descripcion' => 'Daño por impacto (ruptura por golpe)',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            36 => 
            array (
                'id' => 37,
                'codigo' => 'G40',
                'idZona' => 5,
                'descripcion' => 'Filtración de aire por perforación',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            37 => 
            array (
                'id' => 38,
                'codigo' => 'G18',
                'idZona' => 6,
                'descripcion' => 'Abultamiento por filtración de aire',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            38 => 
            array (
                'id' => 39,
                'codigo' => 'G55',
                'idZona' => 6,
                'descripcion' => 'Ruptura lateral en el costado',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            39 => 
            array (
                'id' => 40,
                'codigo' => 'G56',
                'idZona' => 6,
                'descripcion' => 'Ruptura circunferencial en el costado',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            40 => 
            array (
                'id' => 41,
                'codigo' => 'G57',
                'idZona' => 6,
            'descripcion' => 'Separación (abultamiento) en el costado',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            41 => 
            array (
                'id' => 42,
                'codigo' => 'G58',
                'idZona' => 6,
                'descripcion' => 'Daño por roce con objeto cortante',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            42 => 
            array (
                'id' => 43,
                'codigo' => 'G59',
                'idZona' => 6,
                'descripcion' => 'Daño por fricción en el costado',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            43 => 
            array (
                'id' => 44,
                'codigo' => 'G35',
                'idZona' => 7,
                'descripcion' => 'Separación en el hombro en caucho radial',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            44 => 
            array (
                'id' => 45,
                'codigo' => 'G36',
                'idZona' => 7,
                'descripcion' => 'Separación en el hombro en caucho conven',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            45 => 
            array (
                'id' => 46,
                'codigo' => 'G39',
                'idZona' => 8,
                'descripcion' => 'Doblés o ruptura de las lonas en el hombro',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            46 => 
            array (
                'id' => 47,
                'codigo' => 'G21',
                'idZona' => 9,
                'descripcion' => 'Parche no especificado',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            47 => 
            array (
                'id' => 48,
                'codigo' => 'G22',
                'idZona' => 9,
                'descripcion' => 'Grietas o daños en el inner liner no obs',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            48 => 
            array (
                'id' => 49,
                'codigo' => 'G23',
                'idZona' => 9,
                'descripcion' => 'Ampolla en el inner liner',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            49 => 
            array (
                'id' => 50,
                'codigo' => 'G47',
                'idZona' => 9,
            'descripcion' => 'Daño por baja presión (Fatiga, grietas)',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            50 => 
            array (
                'id' => 51,
                'codigo' => 'G48',
                'idZona' => 9,
                'descripcion' => 'Daño en el empate del liner',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            51 => 
            array (
                'id' => 52,
                'codigo' => 'G49',
                'idZona' => 9,
                'descripcion' => 'Grietas en el liner.',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            52 => 
            array (
                'id' => 53,
                'codigo' => 'G50',
                'idZona' => 9,
                'descripcion' => 'Daño con objeto extraño',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            53 => 
            array (
                'id' => 54,
                'codigo' => 'G51',
                'idZona' => 9,
            'descripcion' => 'Separación (abultamiento) ',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            54 => 
            array (
                'id' => 55,
                'codigo' => 'G19',
                'idZona' => 10,
                'descripcion' => 'Filtración de aire por mala de reparació',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            55 => 
            array (
                'id' => 56,
                'codigo' => 'G20',
                'idZona' => 10,
                'descripcion' => 'Reparación defectuoso del talón',
                'procede' => 1,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            56 => 
            array (
                'id' => 57,
                'codigo' => 'G41',
                'idZona' => 10,
                'descripcion' => 'Daños en vuelta de talón',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            57 => 
            array (
                'id' => 58,
                'codigo' => 'G42',
                'idZona' => 10,
                'descripcion' => 'Daños irreparables en capa radial del ta',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            58 => 
            array (
                'id' => 59,
                'codigo' => 'G43',
                'idZona' => 10,
                'descripcion' => 'Daños en el talón, zona de ajuste al rin',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            59 => 
            array (
                'id' => 60,
                'codigo' => 'G44',
                'idZona' => 10,
                'descripcion' => 'Talón quemado',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            60 => 
            array (
                'id' => 61,
                'codigo' => 'G45',
                'idZona' => 10,
                'descripcion' => 'Daño por sobrecalentamiento',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            61 => 
            array (
                'id' => 62,
                'codigo' => 'G46',
                'idZona' => 10,
                'descripcion' => 'Ruptura de la pestaña durante servicio',
                'procede' => 0,
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
        ));
        
        
    }
}