<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RechazoCausaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('rechazo_causa')->delete();
        
        \DB::table('rechazo_causa')->insert(array (
            0 => 
            array (
                'id' => 1,
                'idRechazo' => 1,
                'descripcion' => 'Carcasa con fatiga, baja calidad.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            1 => 
            array (
                'id' => 2,
                'idRechazo' => 1,
                'descripcion' => 'Fin de la vida útil de la carcasa.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            2 => 
            array (
                'id' => 3,
                'idRechazo' => 1,
                'descripcion' => 'Falla en los procesos de revisión inicial, inspección final. ',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            3 => 
            array (
                'id' => 4,
                'idRechazo' => 2,
            'descripcion' => 'No se le asigno la banda adecuada a la carcasa, considerando su calidad, su condición (fatiga), su uso.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            4 => 
            array (
                'id' => 5,
                'idRechazo' => 3,
                'descripcion' => 'Se realizó renovación a carcasa con un serial de producción mayor a lo establecido.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            5 => 
            array (
                'id' => 6,
                'idRechazo' => 4,
            'descripcion' => 'Caucho que sobrepasa los límites de garantía (5 cauchos originales - 18 meses cauchos renovados).',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            6 => 
            array (
                'id' => 7,
                'idRechazo' => 4,
                'descripcion' => 'Carcasa 8 años de límite para renovar por Covencaucho Industrias S.A.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            7 => 
            array (
                'id' => 8,
                'idRechazo' => 5,
                'descripcion' => 'Impacto con objeto, roces con acera, brocal, reductores de velocidad. ',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            8 => 
            array (
                'id' => 9,
                'idRechazo' => 5,
                'descripcion' => 'Sobrecarga.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            9 => 
            array (
                'id' => 10,
                'idRechazo' => 5,
                'descripcion' => 'Baja presión.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            10 => 
            array (
                'id' => 11,
                'idRechazo' => 6,
                'descripcion' => 'Uso de parches y materiales no adecuados para la reparación de perforaciones.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            11 => 
            array (
                'id' => 12,
                'idRechazo' => 6,
                'descripcion' => 'Uso de pedazo de cámara de aire en el área dañada del caucho.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            12 => 
            array (
                'id' => 13,
                'idRechazo' => 7,
            'descripcion' => 'Caucho fuera de servicio, expuesto por largo periodo a condiciones climaticas (sol, lluvia, humedad), agravada por altas',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            13 => 
            array (
                'id' => 14,
                'idRechazo' => 8,
            'descripcion' => 'Caucho en contacto con hidrocarburos (aceite, diesel, grasa, gasolina, kerosene, etc). Caucho expuesto a fuentes de calo',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            14 => 
            array (
                'id' => 15,
                'idRechazo' => 9,
                'descripcion' => 'Rodaje con baja presión / sobrecarga.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            15 => 
            array (
                'id' => 16,
                'idRechazo' => 10,
                'descripcion' => 'Caucho con empates de manufactura pesados que afectan el balanceo.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            16 => 
            array (
                'id' => 17,
                'idRechazo' => 11,
                'descripcion' => 'Liner de mala calidad.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            17 => 
            array (
                'id' => 18,
                'idRechazo' => 11,
                'descripcion' => 'Daño interno con objeto extraño.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            18 => 
            array (
                'id' => 19,
                'idRechazo' => 11,
                'descripcion' => 'Empate del liner abierto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            19 => 
            array (
                'id' => 20,
                'idRechazo' => 11,
                'descripcion' => 'Sobrecarga/Baja presión.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            20 => 
            array (
                'id' => 21,
                'idRechazo' => 12,
                'descripcion' => 'Caucho que tiene presencia de material extraño que migran o quedan encapsulados (Puede ser metal, plástico, madera, goma',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                21 => 
                array (
                    'id' => 22,
                    'idRechazo' => 13,
                    'descripcion' => 'Separación de la banda de rodamiento, por grietas, contaminación.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                22 => 
                array (
                    'id' => 23,
                    'idRechazo' => 14,
                    'descripcion' => 'falla en el proceso de vulcanización.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                23 => 
                array (
                    'id' => 24,
                    'idRechazo' => 15,
                    'descripcion' => 'Mal saneamiento de la reparación.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                24 => 
                array (
                    'id' => 25,
                    'idRechazo' => 15,
                    'descripcion' => 'Mala colocación de parche.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                25 => 
                array (
                    'id' => 26,
                    'idRechazo' => 15,
                'descripcion' => 'Mal raspado (textura).',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                26 => 
                array (
                    'id' => 27,
                    'idRechazo' => 16,
                    'descripcion' => 'Falla en la vulcanización.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                27 => 
                array (
                    'id' => 28,
                    'idRechazo' => 16,
                    'descripcion' => 'Cojín contaminado.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                28 => 
                array (
                    'id' => 29,
                    'idRechazo' => 17,
                    'descripcion' => 'Falla en la vulcanización.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                29 => 
                array (
                    'id' => 30,
                    'idRechazo' => 17,
                    'descripcion' => 'Falla en el compuesto del cojín.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                30 => 
                array (
                    'id' => 31,
                    'idRechazo' => 18,
                    'descripcion' => 'Falla en la vulcanización de la banda preestampada.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                31 => 
                array (
                    'id' => 32,
                    'idRechazo' => 19,
                    'descripcion' => 'Mal manejo y/o almacenaje del cojín.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                32 => 
                array (
                    'id' => 33,
                    'idRechazo' => 19,
                    'descripcion' => 'Contaminación de la carcasa en el proceso de renovado.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                33 => 
                array (
                    'id' => 34,
                    'idRechazo' => 19,
                    'descripcion' => 'Falta de colocación de polietileno en las paradas de planta.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                34 => 
                array (
                    'id' => 35,
                    'idRechazo' => 20,
                    'descripcion' => 'Falla en la inspección de la banda preestampada.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                35 => 
                array (
                    'id' => 36,
                    'idRechazo' => 20,
                    'descripcion' => 'Empate mayor a 5 mm, que presenta porosidad el cojín, despegue de los extremos. ',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                36 => 
                array (
                    'id' => 37,
                    'idRechazo' => 20,
                    'descripcion' => 'Falla en el proceso de embande.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                37 => 
                array (
                    'id' => 38,
                    'idRechazo' => 21,
                    'descripcion' => 'Empate mayor a 5 mm, que presenta porosidad el cojín, despegue de los extremos. ',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                38 => 
                array (
                    'id' => 39,
                    'idRechazo' => 21,
                    'descripcion' => 'Falla en el proceso de embande.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                39 => 
                array (
                    'id' => 40,
                    'idRechazo' => 21,
                    'descripcion' => 'Uso de banda corta.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                40 => 
                array (
                    'id' => 41,
                    'idRechazo' => 22,
                    'descripcion' => 'Despegue de los extremos.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                41 => 
                array (
                    'id' => 42,
                    'idRechazo' => 22,
                    'descripcion' => 'Falla en el proceso de embande.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                42 => 
                array (
                    'id' => 43,
                    'idRechazo' => 22,
                    'descripcion' => 'Contaminación del Camelback.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                43 => 
                array (
                    'id' => 44,
                    'idRechazo' => 22,
                    'descripcion' => 'Uso de Camelback corto.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                44 => 
                array (
                    'id' => 45,
                    'idRechazo' => 23,
                'descripcion' => 'No cumplimiento de la longitud m?nima entre empate y empate (Mínimo 300 mm).',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                45 => 
                array (
                    'id' => 46,
                    'idRechazo' => 24,
                'descripcion' => 'Uso de la banda de rodamiento con largo fuera de especificación (Más largo).',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                46 => 
                array (
                    'id' => 47,
                    'idRechazo' => 24,
                'descripcion' => 'Uso de una banda con exceso de ancho (Más ancho).',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                47 => 
                array (
                    'id' => 48,
                    'idRechazo' => 25,
                    'descripcion' => 'Asignaci?n de banda con el ancho incorrecto.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                48 => 
                array (
                    'id' => 49,
                    'idRechazo' => 25,
                    'descripcion' => 'No se realizó el raspado adecuado.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                49 => 
                array (
                    'id' => 50,
                    'idRechazo' => 26,
                    'descripcion' => 'Problemas en la colocación de la banda en el proceso de embande.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                50 => 
                array (
                    'id' => 51,
                    'idRechazo' => 27,
                    'descripcion' => 'Falla en la vulcanización de la banda de rodamiento.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                51 => 
                array (
                    'id' => 52,
                    'idRechazo' => 27,
                    'descripcion' => 'Falla en la inspección final.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                52 => 
                array (
                    'id' => 53,
                    'idRechazo' => 28,
                    'descripcion' => 'Reparación realizada con materiales no adecuado, personal no calificado.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                53 => 
                array (
                    'id' => 54,
                    'idRechazo' => 29,
                'descripcion' => 'Filtración de aire por reparación inadecuada (parche no autorizado).',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                54 => 
                array (
                    'id' => 55,
                    'idRechazo' => 29,
                    'descripcion' => 'Daño en el liner.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                55 => 
                array (
                    'id' => 56,
                    'idRechazo' => 29,
                    'descripcion' => 'Perforación en el liner y en la banda de rodamiento.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                56 => 
                array (
                    'id' => 57,
                    'idRechazo' => 30,
                    'descripcion' => 'Calentamiento del paquete de correas por fuerte arrastre.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                57 => 
                array (
                    'id' => 58,
                    'idRechazo' => 30,
                    'descripcion' => 'Agresiones repetidas en la banda de rodamiento.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                58 => 
                array (
                    'id' => 59,
                    'idRechazo' => 30,
                    'descripcion' => 'Presiones excesivas en trayectos con piedras.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                59 => 
                array (
                    'id' => 60,
                    'idRechazo' => 31,
                    'descripcion' => 'Falla en la vulcanización, de alguna de las siguientes variables: tiempo de cura, presión, temperatura.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                60 => 
                array (
                    'id' => 61,
                    'idRechazo' => 32,
                    'descripcion' => 'Exceso de relleno, por una lesión fuera de los limites de reparación u hombro caído. ',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                61 => 
                array (
                    'id' => 62,
                    'idRechazo' => 32,
                    'descripcion' => 'Falla en la revisión inicial.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                62 => 
                array (
                    'id' => 63,
                    'idRechazo' => 33,
                    'descripcion' => 'Penetración de húmedad en los cables de acero de la corona por una perforación, una grieta, un corte o retención de pied',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                63 => 
                array (
                    'id' => 64,
                    'idRechazo' => 34,
                    'descripcion' => 'Mal saneamiento de la reparación',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                64 => 
                array (
                    'id' => 65,
                    'idRechazo' => 35,
                'descripcion' => 'Parche no especificado (Tamaño), no centrado, no proporcional a la perforación.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                65 => 
                array (
                    'id' => 66,
                    'idRechazo' => 35,
                    'descripcion' => 'Parche/Cojín/Cemento contaminado o envejecido.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                66 => 
                array (
                    'id' => 67,
                    'idRechazo' => 36,
                    'descripcion' => 'Choque con borde de aceras y brocales, huecos en la carretera, piedra u objeto entre morochas, roce mecánico.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                67 => 
                array (
                    'id' => 68,
                    'idRechazo' => 36,
                    'descripcion' => 'Choques, volcamientos.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                68 => 
                array (
                    'id' => 69,
                    'idRechazo' => 37,
                    'descripcion' => 'Rodaje con perforación no reparada por un largo periodo de tiempo o una larga distancia.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                69 => 
                array (
                    'id' => 70,
                    'idRechazo' => 37,
                    'descripcion' => 'Perforación mal reparada.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                70 => 
                array (
                    'id' => 71,
                    'idRechazo' => 38,
                    'descripcion' => 'Carcasas con separación de material.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                71 => 
                array (
                    'id' => 72,
                    'idRechazo' => 38,
                    'descripcion' => 'Falla en la revisión inicial.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                72 => 
                array (
                    'id' => 73,
                    'idRechazo' => 38,
                    'descripcion' => 'Falla en la inspección final.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                73 => 
                array (
                    'id' => 74,
                    'idRechazo' => 38,
                    'descripcion' => 'La filtración de aire puede ser por una perforación, daño en el liner, mala reparación no detectada en la revisión inici',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                74 => 
                array (
                    'id' => 75,
                    'idRechazo' => 39,
                    'descripcion' => 'Fatiga del caucho por baja presión/sobrecarga.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                75 => 
                array (
                    'id' => 76,
                    'idRechazo' => 39,
                    'descripcion' => 'Rotura de la estructura de la carcasa por ausencia de presi?n con el vehículo no operativo.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                76 => 
                array (
                    'id' => 77,
                    'idRechazo' => 40,
                    'descripcion' => 'Rodaje con caucho perforado/pinchado.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                77 => 
                array (
                    'id' => 78,
                    'idRechazo' => 40,
                    'descripcion' => 'Baja presión.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                78 => 
                array (
                    'id' => 79,
                    'idRechazo' => 40,
                    'descripcion' => 'Sobrecarga.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                79 => 
                array (
                    'id' => 80,
                    'idRechazo' => 41,
                    'descripcion' => 'Aire atrapado en la estructura de la carcasa, calor excesivo o rodaje con baja presión, no presenta perforaciones.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                80 => 
                array (
                    'id' => 81,
                    'idRechazo' => 42,
                    'descripcion' => 'Choque accidental en el lateral del caucho.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                81 => 
                array (
                    'id' => 82,
                    'idRechazo' => 42,
                'descripcion' => 'Objeto atrapado entre los cauchos duales (morochas).',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                82 => 
                array (
                    'id' => 83,
                    'idRechazo' => 43,
                    'descripcion' => 'Perforaciones en la banda de rodamiento que ocasione la perdida de presi?n del caucho  y tenga un roce continuo con otro',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                83 => 
                array (
                    'id' => 84,
                    'idRechazo' => 43,
                    'descripcion' => 'Da?o en el costado que hacen que est?n baja presi?n y tenga un roce continuo con otro caucho o parte mecánica. ',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                84 => 
                array (
                    'id' => 85,
                    'idRechazo' => 43,
                    'descripcion' => 'Rodaje prolongado sin aire o baja presión.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                85 => 
                array (
                    'id' => 86,
                    'idRechazo' => 43,
                    'descripcion' => 'Desgaste en el costado por fricci?n en los ejes duales, por baja presión.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                86 => 
                array (
                    'id' => 87,
                    'idRechazo' => 43,
                    'descripcion' => 'No cumplimiento de la separaci?n mínima entre cauchos duales.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                87 => 
                array (
                    'id' => 88,
                    'idRechazo' => 43,
                    'descripcion' => 'Uso de rines o cauchos disparejos en el eje dual.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                88 => 
                array (
                    'id' => 89,
                    'idRechazo' => 43,
                    'descripcion' => 'Roces continuo con aceras, brocales, partes mecanicas de la carrocería',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                89 => 
                array (
                    'id' => 90,
                    'idRechazo' => 44,
                    'descripcion' => 'Maniobras forzadas.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                90 => 
                array (
                    'id' => 91,
                    'idRechazo' => 44,
                    'descripcion' => 'Diseño incorrecto para eje de arrastre.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                91 => 
                array (
                    'id' => 92,
                    'idRechazo' => 45,
                    'descripcion' => 'Rodaje con presión baja por largo trayectos.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                92 => 
                array (
                    'id' => 93,
                    'idRechazo' => 45,
                    'descripcion' => 'Fatiga de la estructura del caucho por sobrecarga/baja presión.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                93 => 
                array (
                    'id' => 94,
                    'idRechazo' => 45,
                    'descripcion' => 'Maniobras con arrastre lateral.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                94 => 
                array (
                    'id' => 95,
                    'idRechazo' => 45,
                    'descripcion' => 'Impacto con obstáculos en el trayecto, con filos de acera, borcales, huecos en carreteras.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                95 => 
                array (
                    'id' => 96,
                    'idRechazo' => 46,
                    'descripcion' => 'Daños provenientes de las oxidaciones de los cables de acero.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                96 => 
                array (
                    'id' => 97,
                    'idRechazo' => 46,
                    'descripcion' => 'Oxidación del paquete de correas en la corona.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                97 => 
                array (
                    'id' => 98,
                    'idRechazo' => 46,
                    'descripcion' => 'Descargas eléctricas, etc.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                98 => 
                array (
                    'id' => 99,
                    'idRechazo' => 47,
                    'descripcion' => 'Se usó un parche CVC no especificado para la dimesión de la lesión/perforación.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                99 => 
                array (
                    'id' => 100,
                    'idRechazo' => 48,
                    'descripcion' => 'Liner de mala calidad.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                100 => 
                array (
                    'id' => 101,
                    'idRechazo' => 48,
                    'descripcion' => 'Daño interno con objeto extraño.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                101 => 
                array (
                    'id' => 102,
                    'idRechazo' => 48,
                    'descripcion' => 'Empate del liner abierto.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                102 => 
                array (
                    'id' => 103,
                    'idRechazo' => 48,
                    'descripcion' => 'Sobrecarga/Baja presión.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                103 => 
                array (
                    'id' => 104,
                    'idRechazo' => 49,
                    'descripcion' => 'Material extraño en el inner liner.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                104 => 
                array (
                    'id' => 105,
                    'idRechazo' => 49,
                    'descripcion' => 'Filtración de aire. ',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                105 => 
                array (
                    'id' => 106,
                    'idRechazo' => 49,
                    'descripcion' => 'Separación de los materiales en el proceso de vulcanización.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                106 => 
                array (
                    'id' => 107,
                    'idRechazo' => 49,
                    'descripcion' => 'Falla en la revisión inicial e inspeccion final.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                107 => 
                array (
                    'id' => 108,
                    'idRechazo' => 50,
                    'descripcion' => 'Rodaje con baja presión.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                108 => 
                array (
                    'id' => 109,
                    'idRechazo' => 50,
                    'descripcion' => 'Sobrecarga.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                109 => 
                array (
                    'id' => 110,
                    'idRechazo' => 50,
                    'descripcion' => 'Perforación / Pinchazo.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                110 => 
                array (
                    'id' => 111,
                    'idRechazo' => 51,
                    'descripcion' => 'Impacto.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                111 => 
                array (
                    'id' => 112,
                    'idRechazo' => 51,
                'descripcion' => 'Mala calidad del liner (Capa de butilo).',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                112 => 
                array (
                    'id' => 113,
                    'idRechazo' => 51,
                'descripcion' => 'Empate de liner abierto (defecto de manufactura del caucho original).',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                113 => 
                array (
                    'id' => 114,
                    'idRechazo' => 52,
                    'descripcion' => 'Liner de mala calidad.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                114 => 
                array (
                    'id' => 115,
                    'idRechazo' => 52,
                'descripcion' => 'Empate de liner abierto (defecto de manufactura del caucho original).',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                115 => 
                array (
                    'id' => 116,
                    'idRechazo' => 52,
                    'descripcion' => 'Sobrecarga/Baja presión.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                116 => 
                array (
                    'id' => 117,
                    'idRechazo' => 53,
                    'descripcion' => 'Daño por roce de válvula.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                117 => 
                array (
                    'id' => 118,
                    'idRechazo' => 53,
                    'descripcion' => 'Daño interno por objeto extra?o.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                118 => 
                array (
                    'id' => 119,
                    'idRechazo' => 53,
                    'descripcion' => 'Daño con el rin.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                119 => 
                array (
                    'id' => 120,
                    'idRechazo' => 54,
                    'descripcion' => 'Perdida de adherencia del material de revestimiento interno del caucho, debido al calentamiento excesivo, ancho de rin i',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                120 => 
                array (
                    'id' => 121,
                    'idRechazo' => 54,
                    'descripcion' => 'Filtración de aire en la estructura del caucho.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                121 => 
                array (
                    'id' => 122,
                    'idRechazo' => 55,
                    'descripcion' => 'Reparación irregular del tal?n que presentaba daño en la capa de butilo.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                122 => 
                array (
                    'id' => 123,
                    'idRechazo' => 56,
                    'descripcion' => 'Reparación irregular del tal?n',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                123 => 
                array (
                    'id' => 124,
                    'idRechazo' => 56,
                    'descripcion' => 'No se realizó en saneo adecuado.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                124 => 
                array (
                    'id' => 125,
                    'idRechazo' => 56,
                    'descripcion' => 'No hubo adherencia de la goma y filtró aire.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                125 => 
                array (
                    'id' => 126,
                    'idRechazo' => 57,
                    'descripcion' => 'Fatiga en la carcasa, por sobrecarga o baja presión.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                126 => 
                array (
                    'id' => 127,
                    'idRechazo' => 57,
                    'descripcion' => 'Mal posicionamento del caucho sobre el rin.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                127 => 
                array (
                    'id' => 128,
                    'idRechazo' => 58,
                'descripcion' => 'Procedimiento inadecuado en el montaje/desmontaje (Herramienta, Personal no calificado, lubricante no adecuado)',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                128 => 
                array (
                    'id' => 129,
                    'idRechazo' => 59,
                'descripcion' => 'Procedimiento inadecuado en el montaje/desmontaje (Herramienta, Personal no calificado, lubricante no adecuado)',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                129 => 
                array (
                    'id' => 130,
                    'idRechazo' => 60,
                    'descripcion' => 'Sobrecalentamiento por sistema de freno.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                130 => 
                array (
                    'id' => 131,
                    'idRechazo' => 61,
                    'descripcion' => 'Sobrecarga.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                131 => 
                array (
                    'id' => 132,
                    'idRechazo' => 61,
                    'descripcion' => 'Baja presión.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                132 => 
                array (
                    'id' => 133,
                    'idRechazo' => 61,
                    'descripcion' => 'Ancho de rin inadecuado.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                133 => 
                array (
                    'id' => 134,
                    'idRechazo' => 61,
                    'descripcion' => 'Sobrecalentamiento por sistema de freno.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                134 => 
                array (
                    'id' => 135,
                    'idRechazo' => 62,
                    'descripcion' => 'Una ruptura parcial durante el rodaje. ',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                135 => 
                array (
                    'id' => 136,
                    'idRechazo' => 62,
                    'descripcion' => 'Choque accidental.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                136 => 
                array (
                    'id' => 137,
                    'idRechazo' => 62,
                    'descripcion' => 'Impacto contra obstáculos.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
                137 => 
                array (
                    'id' => 138,
                    'idRechazo' => 62,
                    'descripcion' => 'Descarga eléctrica.',
                    'activo' => 1,
                    'estado' => 0,
                    'idUsuario' => 1,
                    'created_at' => '2022-01-09 16:25:17',
                    'updated_at' => '2022-01-09 16:25:17',
                ),
            ));
        
        
    }
}