<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RechazoRecomendacionTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('rechazo_recomendacion')->delete();
        
        \DB::table('rechazo_recomendacion')->insert(array (
            0 => 
            array (
                'id' => 1,
                'idRechazo' => 1,
                'descripcion' => 'Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 17:35:56',
            ),
            1 => 
            array (
                'id' => 2,
                'idRechazo' => 1,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            2 => 
            array (
                'id' => 3,
                'idRechazo' => 2,
                'descripcion' => 'Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            3 => 
            array (
                'id' => 4,
                'idRechazo' => 2,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            4 => 
            array (
                'id' => 5,
                'idRechazo' => 3,
                'descripcion' => 'Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            5 => 
            array (
                'id' => 6,
                'idRechazo' => 3,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            6 => 
            array (
                'id' => 7,
                'idRechazo' => 4,
                'descripcion' => 'Revisar la fecha de fabricación de los cauchos.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            7 => 
            array (
                'id' => 8,
                'idRechazo' => 4,
                'descripcion' => 'Aprovechamiento de los cauchos durante el lapso de cobertura de la garantía.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            8 => 
            array (
                'id' => 9,
                'idRechazo' => 5,
                'descripcion' => 'Extremar la precaución y el cuidado con los roces con bordes, superficies salientes e impactos en carretera.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            9 => 
            array (
                'id' => 10,
                'idRechazo' => 5,
                'descripcion' => 'Revisar las presiones de inflado en relación a la carga. ',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            10 => 
            array (
                'id' => 11,
                'idRechazo' => 5,
                'descripcion' => 'Comprobar las presiones regularmente. Siempre calibrar los cauchos en frío.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            11 => 
            array (
                'id' => 12,
                'idRechazo' => 5,
                'descripcion' => 'Realizar análisis técnico de repartición de carga y presión de inflado con técnicos autorizados de Covencaucho Industrias.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            12 => 
            array (
                'id' => 13,
                'idRechazo' => 6,
                'descripcion' => ' Realizar las reparaciones con los materiales adecuados y personas calificadas.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            13 => 
            array (
                'id' => 14,
                'idRechazo' => 6,
                'descripcion' => 'Preferiblemente hacer la reparación en un centro de servicio técnico.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            14 => 
            array (
                'id' => 15,
                'idRechazo' => 6,
                'descripcion' => 'Seguir las orientaciones técnicas de uso de los cauchos y rines conforme a los fabricantes.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            15 => 
            array (
                'id' => 16,
                'idRechazo' => 6,
                'descripcion' => 'Hacer uso del caucho de respuesto, para reemplazos en carretera.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            16 => 
            array (
                'id' => 17,
                'idRechazo' => 7,
                'descripcion' => 'Revisar la fecha de fabricación de los cauchos.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            17 => 
            array (
                'id' => 18,
                'idRechazo' => 7,
            'descripcion' => 'Evitar dejar los cauchos a la intemperie cuando el vehículo no este operativo, es recomendable que este bajo sombra y no dejar con baja presión (espichado), para evitar daños en la goma.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            18 => 
            array (
                'id' => 19,
                'idRechazo' => 8,
                'descripcion' => 'No limpiar o pintar los cauchos con productos químicos o derivados de hidrocarburos.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            19 => 
            array (
                'id' => 20,
                'idRechazo' => 8,
                'descripcion' => 'No almacenar los cauchos en lugares expuestos a fuentes de calor, cómo máquinas de soldar, generadores eléctricos, descargas electricas, etc.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            20 => 
            array (
                'id' => 21,
                'idRechazo' => 9,
                'descripcion' => 'Revisar las presiones de inflado en relación a la carga. ',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            21 => 
            array (
                'id' => 22,
                'idRechazo' => 9,
                'descripcion' => 'Comprobar las presiones regularmente. Siempre calibrar los cauchos en frío.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            22 => 
            array (
                'id' => 23,
                'idRechazo' => 9,
                'descripcion' => 'Realizar análisis técnico de repartición de carga y presión de inflado con t?cnicos autorizados de Covencaucho Industrias.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            23 => 
            array (
                'id' => 24,
                'idRechazo' => 10,
                'descripcion' => 'Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            24 => 
            array (
                'id' => 25,
                'idRechazo' => 10,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            25 => 
            array (
                'id' => 26,
                'idRechazo' => 11,
                'descripcion' => ' Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            26 => 
            array (
                'id' => 27,
                'idRechazo' => 11,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            27 => 
            array (
                'id' => 28,
                'idRechazo' => 12,
                'descripcion' => 'Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            28 => 
            array (
                'id' => 29,
                'idRechazo' => 12,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            29 => 
            array (
                'id' => 30,
                'idRechazo' => 13,
                'descripcion' => ' Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            30 => 
            array (
                'id' => 31,
                'idRechazo' => 13,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            31 => 
            array (
                'id' => 32,
                'idRechazo' => 14,
                'descripcion' => 'Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            32 => 
            array (
                'id' => 33,
                'idRechazo' => 14,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            33 => 
            array (
                'id' => 34,
                'idRechazo' => 15,
                'descripcion' => 'Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            34 => 
            array (
                'id' => 35,
                'idRechazo' => 15,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            35 => 
            array (
                'id' => 36,
                'idRechazo' => 16,
                'descripcion' => 'Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            36 => 
            array (
                'id' => 37,
                'idRechazo' => 16,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            37 => 
            array (
                'id' => 38,
                'idRechazo' => 17,
                'descripcion' => 'Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            38 => 
            array (
                'id' => 39,
                'idRechazo' => 17,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            39 => 
            array (
                'id' => 40,
                'idRechazo' => 18,
                'descripcion' => 'Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            40 => 
            array (
                'id' => 41,
                'idRechazo' => 18,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            41 => 
            array (
                'id' => 42,
                'idRechazo' => 19,
                'descripcion' => ' Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            42 => 
            array (
                'id' => 43,
                'idRechazo' => 19,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            43 => 
            array (
                'id' => 44,
                'idRechazo' => 20,
                'descripcion' => ' Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            44 => 
            array (
                'id' => 45,
                'idRechazo' => 20,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            45 => 
            array (
                'id' => 46,
                'idRechazo' => 21,
                'descripcion' => ' Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            46 => 
            array (
                'id' => 47,
                'idRechazo' => 21,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            47 => 
            array (
                'id' => 48,
                'idRechazo' => 22,
                'descripcion' => 'Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            48 => 
            array (
                'id' => 49,
                'idRechazo' => 22,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            49 => 
            array (
                'id' => 50,
                'idRechazo' => 23,
                'descripcion' => 'Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            50 => 
            array (
                'id' => 51,
                'idRechazo' => 23,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            51 => 
            array (
                'id' => 52,
                'idRechazo' => 24,
                'descripcion' => 'Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            52 => 
            array (
                'id' => 53,
                'idRechazo' => 24,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            53 => 
            array (
                'id' => 54,
                'idRechazo' => 25,
                'descripcion' => ' Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            54 => 
            array (
                'id' => 55,
                'idRechazo' => 25,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            55 => 
            array (
                'id' => 56,
                'idRechazo' => 26,
                'descripcion' => 'Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            56 => 
            array (
                'id' => 57,
                'idRechazo' => 26,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            57 => 
            array (
                'id' => 58,
                'idRechazo' => 27,
                'descripcion' => 'Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            58 => 
            array (
                'id' => 59,
                'idRechazo' => 27,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            59 => 
            array (
                'id' => 60,
                'idRechazo' => 28,
                'descripcion' => 'Realizar las reparaciones con los materiales adecuados y personas calificadas.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            60 => 
            array (
                'id' => 61,
                'idRechazo' => 28,
                'descripcion' => 'Preferiblemente hacer la reparacion en un centro de servicio técnico. ',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            61 => 
            array (
                'id' => 62,
                'idRechazo' => 29,
                'descripcion' => 'Realizar las reparaciones con los materiales adecuados y personas calificadas.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            62 => 
            array (
                'id' => 63,
                'idRechazo' => 29,
                'descripcion' => 'Preferiblemente hacer la reparacion en un centro de servicio técnico. ',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            63 => 
            array (
                'id' => 64,
                'idRechazo' => 29,
                'descripcion' => 'Seguir las orientaciones técnicas de uso de los cauchos y rines conforme a los fabricantes.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            64 => 
            array (
                'id' => 65,
                'idRechazo' => 29,
                'descripcion' => 'Inspeccionar diariamente los cauchos del vehículo, este proceso permite detectar alguna perforación a tiempo y así recuperar el caucho.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            65 => 
            array (
                'id' => 66,
                'idRechazo' => 30,
                'descripcion' => 'Calibrar los cauchos periodicamente, siempre en frío.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            66 => 
            array (
                'id' => 67,
                'idRechazo' => 30,
                'descripcion' => 'Realizar análisis t?cnico de repartición de carga y presión de inflado con técnicos autorizados de Covencaucho Industrias. ',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            67 => 
            array (
                'id' => 68,
                'idRechazo' => 31,
                'descripcion' => 'Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            68 => 
            array (
                'id' => 69,
                'idRechazo' => 31,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            69 => 
            array (
                'id' => 70,
                'idRechazo' => 32,
                'descripcion' => 'Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            70 => 
            array (
                'id' => 71,
                'idRechazo' => 32,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            71 => 
            array (
                'id' => 72,
                'idRechazo' => 33,
                'descripcion' => 'Evitar daños por perforaciones o impactos del caucho en la corona, donde se exponga los cables de acero de las correas.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            72 => 
            array (
                'id' => 73,
                'idRechazo' => 33,
                'descripcion' => 'Evitar la retención de piedras en los surcos de la banda de rodamiento, que generen alguna perforación.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            73 => 
            array (
                'id' => 74,
                'idRechazo' => 33,
                'descripcion' => 'Inspeccionar los cauchos regularmente y retirar las piedras de los surcos.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            74 => 
            array (
                'id' => 75,
                'idRechazo' => 34,
                'descripcion' => 'Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            75 => 
            array (
                'id' => 76,
                'idRechazo' => 34,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            76 => 
            array (
                'id' => 77,
                'idRechazo' => 35,
                'descripcion' => 'Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            77 => 
            array (
                'id' => 78,
                'idRechazo' => 35,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            78 => 
            array (
                'id' => 79,
                'idRechazo' => 36,
                'descripcion' => 'Extremar la precaución y el cuidado con los roces con bordes o superficies salientes.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            79 => 
            array (
                'id' => 80,
                'idRechazo' => 36,
                'descripcion' => 'Evitar los impactos con obstáculos en la vía con huecos, reductores de velocidad, aceras, brocales.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            80 => 
            array (
                'id' => 81,
                'idRechazo' => 37,
                'descripcion' => 'Inspeccionar diariamente los cauchos del vehículo, este proceso permite detectar alguna perforación o daños, a tiempo y así recuperar el caucho.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            81 => 
            array (
                'id' => 82,
                'idRechazo' => 37,
                'descripcion' => 'Realizar las reparaciones con los materiales adecuados y personas calificadas.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            82 => 
            array (
                'id' => 83,
                'idRechazo' => 37,
                'descripcion' => 'Preferiblemente hacer la reparación en un centro de servicio técnico.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            83 => 
            array (
                'id' => 84,
                'idRechazo' => 37,
                'descripcion' => 'Seguir las orientaciones técnicas de uso de los cauchos y rines conforme a los fabricantes.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            84 => 
            array (
                'id' => 85,
                'idRechazo' => 37,
                'descripcion' => 'Hacer uso del caucho de respuesto, para reemplazos en carretera.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            85 => 
            array (
                'id' => 86,
                'idRechazo' => 38,
                'descripcion' => 'Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            86 => 
            array (
                'id' => 87,
                'idRechazo' => 38,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            87 => 
            array (
                'id' => 88,
                'idRechazo' => 39,
                'descripcion' => 'Revisar las presiones de inflado en relación a la carga. ',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            88 => 
            array (
                'id' => 89,
                'idRechazo' => 39,
                'descripcion' => 'Comprobar las presiones regularmente. Siempre calibrar los cauchos en frío.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            89 => 
            array (
                'id' => 90,
                'idRechazo' => 39,
                'descripcion' => 'Realizar análisis técnico de repartición de carga y presión de inflado con técnicos autorizados de Covencaucho Industrias.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            90 => 
            array (
                'id' => 91,
                'idRechazo' => 40,
                'descripcion' => 'Inspeccionar diariamente los cauchos del vehículo, este proceso permite detectar alguna perforación o daño en lel costado a tiempo y así recuperar el caucho.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            91 => 
            array (
                'id' => 92,
                'idRechazo' => 40,
                'descripcion' => 'Revisar las presiones de inflado en relación a la carga. ',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            92 => 
            array (
                'id' => 93,
                'idRechazo' => 40,
                'descripcion' => 'Comprobar las presiones regularmente. Siempre calibrar los cauchos en frío.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            93 => 
            array (
                'id' => 94,
                'idRechazo' => 40,
                'descripcion' => 'Realizar análisis técnico de repartición de carga y presión de inflado con técnicos autorizados de Covencaucho Industrias.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            94 => 
            array (
                'id' => 95,
                'idRechazo' => 41,
                'descripcion' => 'Revisar las presiones de inflado en relación a la carga. ',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            95 => 
            array (
                'id' => 96,
                'idRechazo' => 41,
                'descripcion' => 'Comprobar las presiones regularmente. Siempre calibrar los cauchos en frío.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            96 => 
            array (
                'id' => 97,
                'idRechazo' => 41,
                'descripcion' => 'Realizar análisis técnico de repartición de carga y presión de inflado con técnicos autorizados de Covencaucho Industrias.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            97 => 
            array (
                'id' => 98,
                'idRechazo' => 42,
                'descripcion' => 'Extremar la precaución y el cuidado con los roces con bordes de las aceras, brocales o superficies salientes.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            98 => 
            array (
                'id' => 99,
                'idRechazo' => 42,
                'descripcion' => 'Inspeccionar diariamente los cauchos del vehículo, este proceso permite detectar alguna perforación, roce o daños, a tiempo y así recuperar el caucho.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            99 => 
            array (
                'id' => 100,
                'idRechazo' => 43,
                'descripcion' => 'Inspeccionar diariamente los cauchos del vehículo, este proceso permite detectar alguna perforación, roce o daños, a tiempo y así recuperar el caucho.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            100 => 
            array (
                'id' => 101,
                'idRechazo' => 43,
                'descripcion' => 'Correcto uso del ancho de los rines en los ejes duales.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            101 => 
            array (
                'id' => 102,
                'idRechazo' => 43,
                'descripcion' => 'Cumplir con el espacio m?nimo entre cauchos duales, uso correcto del espaciador.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            102 => 
            array (
                'id' => 103,
                'idRechazo' => 43,
                'descripcion' => 'Inspeccionar continuamente las presiones de aire de los cauchos, en frío.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            103 => 
            array (
                'id' => 104,
                'idRechazo' => 44,
            'descripcion' => 'Uso de cauchos de diseño de arratre (Hombros redondos), para disminuir la fuera lateral por arrastre en los vehículos motrices.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            104 => 
            array (
                'id' => 105,
                'idRechazo' => 45,
                'descripcion' => 'Calibrar los cauchos periodicamente, siempre en frío.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            105 => 
            array (
                'id' => 106,
                'idRechazo' => 45,
            'descripcion' => 'Uso de cauchos de diseño de arratre (Hombros redondos), para disminuir la fuera lateral por arrastre en los vehículos de arrastre.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            106 => 
            array (
                'id' => 107,
                'idRechazo' => 45,
                'descripcion' => 'Extremar la precaución y el cuidado con los roces con bordes o superficies salientes.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            107 => 
            array (
                'id' => 108,
                'idRechazo' => 45,
                'descripcion' => 'Evitar los impactos con obtaculos en la vía con huecos, reductores de velocidad, aceras, brocales.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            108 => 
            array (
                'id' => 109,
                'idRechazo' => 46,
                'descripcion' => 'Evitar daños por perforaciones o impactos del caucho en la corona, donde se exponga los cables de acero de las correas.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            109 => 
            array (
                'id' => 110,
                'idRechazo' => 46,
                'descripcion' => 'Evitar la retención de piedras en los surcos de la banda de rodamiento, que generen alguna perforación.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            110 => 
            array (
                'id' => 111,
                'idRechazo' => 46,
                'descripcion' => 'Inspeccionar los cauchos regularmente y retirar las piedras de los surcos.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            111 => 
            array (
                'id' => 112,
                'idRechazo' => 46,
                'descripcion' => 'Evitar descargas electricas sobre los cauchos.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            112 => 
            array (
                'id' => 113,
                'idRechazo' => 47,
                'descripcion' => 'Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            113 => 
            array (
                'id' => 114,
                'idRechazo' => 47,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            114 => 
            array (
                'id' => 115,
                'idRechazo' => 48,
                'descripcion' => 'Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            115 => 
            array (
                'id' => 116,
                'idRechazo' => 48,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            116 => 
            array (
                'id' => 117,
                'idRechazo' => 49,
                'descripcion' => 'Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            117 => 
            array (
                'id' => 118,
                'idRechazo' => 49,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            118 => 
            array (
                'id' => 119,
                'idRechazo' => 50,
                'descripcion' => 'Revisar las presiones de inflado en relación a la carga. ',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            119 => 
            array (
                'id' => 120,
                'idRechazo' => 50,
                'descripcion' => 'Comprobar las presiones regularmente. Siempre calibrar los cauchos en frío.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            120 => 
            array (
                'id' => 121,
                'idRechazo' => 50,
                'descripcion' => 'Realizar análisis técnico de repartición de carga y presión de inflado con técnicos autorizados de Covencaucho Industrias.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            121 => 
            array (
                'id' => 122,
                'idRechazo' => 50,
                'descripcion' => 'Extremar la precaución y el cuidado, para evitar perforaciones, cortes e impactos en carretera.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            122 => 
            array (
                'id' => 123,
                'idRechazo' => 51,
                'descripcion' => 'Extremar la precaución y el cuidado, para evitar impactos en carretera.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            123 => 
            array (
                'id' => 124,
                'idRechazo' => 51,
                'descripcion' => 'Usar cauchos de mayor calidad.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            124 => 
            array (
                'id' => 125,
                'idRechazo' => 52,
                'descripcion' => 'Revisar las presiones de inflado en relación a la carga. ',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            125 => 
            array (
                'id' => 126,
                'idRechazo' => 52,
                'descripcion' => 'Comprobar las presiones regularmente. Siempre calibrar los cauchos en frío.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            126 => 
            array (
                'id' => 127,
                'idRechazo' => 53,
                'descripcion' => 'Usar la cámara adecuada y el rin adecuado.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            127 => 
            array (
                'id' => 128,
                'idRechazo' => 53,
                'descripcion' => 'En el montaje no coloque objetos extraños dentro del conjunto caucho-rin.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            128 => 
            array (
                'id' => 129,
                'idRechazo' => 54,
                'descripcion' => 'Seguir las orientaciones técnicas para elegir el ancho de rin correcto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            129 => 
            array (
                'id' => 130,
                'idRechazo' => 54,
                'descripcion' => 'Calentamiento del talón causado por el uso excesivo del freno.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            130 => 
            array (
                'id' => 131,
                'idRechazo' => 54,
                'descripcion' => 'Realizar mantenimiento preventivo al sistema de frenos del vehículo.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            131 => 
            array (
                'id' => 132,
                'idRechazo' => 54,
                'descripcion' => 'Realizar entrenamiento a los conductores.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            132 => 
            array (
                'id' => 133,
                'idRechazo' => 54,
                'descripcion' => 'Realizar las reparaciones por perforación en un centro de servicio técnico, para evitar filtración por aire.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            133 => 
            array (
                'id' => 134,
                'idRechazo' => 55,
                'descripcion' => 'Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            134 => 
            array (
                'id' => 135,
                'idRechazo' => 55,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            135 => 
            array (
                'id' => 136,
                'idRechazo' => 56,
                'descripcion' => 'Realizar análisis de falla del defecto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            136 => 
            array (
                'id' => 137,
                'idRechazo' => 56,
                'descripcion' => 'Tomar acciones correctivas en el proceso de renovado y su personal.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            137 => 
            array (
                'id' => 138,
                'idRechazo' => 57,
                'descripcion' => 'Revisar las presiones de inflado en relación a la carga. ',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            138 => 
            array (
                'id' => 139,
                'idRechazo' => 57,
                'descripcion' => 'Comprobar las presiones regularmente. Siempre calibrar los cauchos en frío.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            139 => 
            array (
                'id' => 140,
                'idRechazo' => 57,
                'descripcion' => 'Realizar análisis técnico de repartición de carga y presión de inflado con técnicos autorizados de Covencaucho Industrias.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            140 => 
            array (
                'id' => 141,
                'idRechazo' => 57,
                'descripcion' => 'Realizar el correcto ensamble de caucho-rin, para que quede centrado.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            141 => 
            array (
                'id' => 142,
                'idRechazo' => 57,
                'descripcion' => 'Seguir las orientaciones técnicas de uso de los cauchos y rines conforme a los fabricantes.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            142 => 
            array (
                'id' => 143,
                'idRechazo' => 58,
                'descripcion' => 'Realizar los montajes y desmontajes con las herramientas adecuadas, lubricante adecuado y personas calificadas.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            143 => 
            array (
                'id' => 144,
                'idRechazo' => 58,
                'descripcion' => 'Preferiblemente hacer el montaje en un centro de servicio técnico.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            144 => 
            array (
                'id' => 145,
                'idRechazo' => 58,
                'descripcion' => 'Seguir las orientaciones técnicas de uso de los cauchos y rines conforme a los fabricantes.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            145 => 
            array (
                'id' => 146,
                'idRechazo' => 59,
                'descripcion' => 'Realizar los montajes y desmontajes con las herramientas adecuadas, lubricante adecuado y personas calificadas.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            146 => 
            array (
                'id' => 147,
                'idRechazo' => 59,
                'descripcion' => 'Preferiblemente hacer el montaje en un centro de servicio técnico.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            147 => 
            array (
                'id' => 148,
                'idRechazo' => 59,
                'descripcion' => 'Seguir las orientaciones técnicas de uso de los cauchos y rines conforme a los fabricantes.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            148 => 
            array (
                'id' => 149,
                'idRechazo' => 60,
                'descripcion' => 'Calentamiento del talón causado por el uso excesivo del freno.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            149 => 
            array (
                'id' => 150,
                'idRechazo' => 60,
                'descripcion' => 'Descarga electrica.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            150 => 
            array (
                'id' => 151,
                'idRechazo' => 60,
                'descripcion' => 'Mala regulación de los frenos, etc.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            151 => 
            array (
                'id' => 152,
                'idRechazo' => 60,
                'descripcion' => 'Realizar mantenimiento preventivo al sistema de frenos del vehículo.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            152 => 
            array (
                'id' => 153,
                'idRechazo' => 60,
                'descripcion' => 'Realizar entrenamiento a los conductores.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            153 => 
            array (
                'id' => 154,
                'idRechazo' => 61,
                'descripcion' => 'Revisar las presiones de inflado en relación a la carga. ',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            154 => 
            array (
                'id' => 155,
                'idRechazo' => 61,
                'descripcion' => 'Comprobar las presiones regularmente. Siempre calibrar los cauchos en frío.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            155 => 
            array (
                'id' => 156,
                'idRechazo' => 61,
                'descripcion' => 'Realizar análisis técnico de repartición de carga y presión de inflado con técnicos autorizados de Covencaucho Industrias.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            156 => 
            array (
                'id' => 157,
                'idRechazo' => 61,
                'descripcion' => 'Seguir las orientaciones técnicas para elegir el ancho de rin correcto.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            157 => 
            array (
                'id' => 158,
                'idRechazo' => 61,
                'descripcion' => 'Calentamiento del talón causado por el uso excesivo del freno.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            158 => 
            array (
                'id' => 159,
                'idRechazo' => 61,
                'descripcion' => 'Descarga electrica.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            159 => 
            array (
                'id' => 160,
                'idRechazo' => 61,
                'descripcion' => 'Mala regulación de los frenos, etc.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            160 => 
            array (
                'id' => 161,
                'idRechazo' => 61,
                'descripcion' => 'Realizar mantenimiento preventivo al sistema de frenos del vehículo.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            161 => 
            array (
                'id' => 162,
                'idRechazo' => 61,
                'descripcion' => 'Realizar entrenamiento a los conductores.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            162 => 
            array (
                'id' => 163,
                'idRechazo' => 62,
                'descripcion' => 'Extremar la precaución y el cuidado, para evitar perforaciones, cortes e impactos en carretera.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            163 => 
            array (
                'id' => 164,
                'idRechazo' => 62,
                'descripcion' => 'Evitar descargas electricas sobre los cauchos.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
            164 => 
            array (
                'id' => 165,
                'idRechazo' => 30,
                'descripcion' => 'Inspeccionar los cauchos regularmente.',
                'activo' => 1,
                'estado' => 0,
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
            ),
        ));
        
        
    }
}