<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SucursalTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('sucursal')->delete();
        
        \DB::table('sucursal')->insert(array (
            0 => 
            array (
                'id' => 1,
                'codigo' => 'C01',
                'descripcion' => 'Covencaucho Industrias, S.A.',
                'principal' => 1,
                'direccion' => 'ZONA INDUSTRIAL II CARRERA 1 CON CALLE 4 COVENCAUCHO 1, BARQUISIMETO, EDO. LARA',
                'correo' => 'mercadeo@covencaucho.com',
                'telefono' => '251-2601331 / 2601339',
                'activo' => 1,
                'estado' => 0,
                'servidor' => '3.14.204.63',
                'puerto' => '3306',
                'bd' => 'saintac01',
                'usuario' => 'sa',
                'clave' => 'dobermann2021',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => 'J085037667',
            ),
            1 => 
            array (
                'id' => 2,
                'codigo' => 'A29',
                'descripcion' => 'Agrocauchos La Pascua, S.A.',
                'principal' => 0,
                'direccion' => 'MANAPIRE SUR ZONA INDUSTRIAL LOCAL NRO 33-1 VALLE DE LA PASCUA EDO GUARICO   
(+58) 0235-3420014               ',
                'correo' => 'agrocauchoslapascua@gmail.com',
                'telefono' => '0414-1485774',
                'activo' => 1,
                'estado' => 0,
                'servidor' => '3.14.204.63',
                'puerto' => '3306',
                'bd' => 'sainta29',
                'usuario' => 'sa',
                'clave' => 'dobermann2021',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => 'J315672650',
            ),
            2 => 
            array (
                'id' => 3,
                'codigo' => 'A35',
                'descripcion' => 'Anita Cauchos, S.A.',
                'principal' => 0,
                'direccion' => 'CTRA NACIONAL GUARENAS-GUATIRE GALPON SIN NUMERO SECTOR EL INGENIO     
(+58) 0212-3810230                     ',
                'correo' => 'anitacauchos@gmail.com',
                'telefono' => '0414-5462863',
                'activo' => 1,
                'estado' => 0,
                'servidor' => '3.14.204.63',
                'puerto' => '3306',
                'bd' => 'sainta35',
                'usuario' => 'sa',
                'clave' => 'dobermann2021',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => 'J293937299',
            ),
            3 => 
            array (
                'id' => 4,
                'codigo' => 'A34',
                'descripcion' => 'Atlantic Tires, C.A.',
                'principal' => 0,
                'direccion' => 'CALLE 137 CC PROFESIONAL MONTE BIANCO NIVEL 1 OF.51 URB. LOS SAUCES VALENCIA CARABOBO       ',
                'correo' => 'atlantictiresventas@gmail.com',
                'telefono' => '0414-4824557    ',
                'activo' => 0,
                'estado' => 0,
                'servidor' => '3.14.204.63',
                'puerto' => '3306',
                'bd' => 'sainta34',
                'usuario' => 'sa',
                'clave' => 'dobermann2021',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => 'J404644954',
            ),
            4 => 
            array (
                'id' => 5,
                'codigo' => 'A50',
                'descripcion' => 'Cauchos Centrooccidente, C.A.',
                'principal' => 0,
                'direccion' => 'AV INTERCOMUNAL ACARIGUA- BARQUISIMETO CASA NRO S/N ZONA BARQUISIMETO                       ',
                'correo' => 'cauchoscentrooccidente@gmail.com',
                'telefono' => '0414-3507484',
                'activo' => 1,
                'estado' => 0,
                'servidor' => '3.14.204.63',
                'puerto' => '3306',
                'bd' => 'sainta50',
                'usuario' => 'sa',
                'clave' => 'dobermann2021',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => 'J298922796',
            ),
            5 => 
            array (
                'id' => 6,
                'codigo' => 'A46',
                'descripcion' => 'Cauchos Cumanagoto, S.A.',
                'principal' => 0,
                'direccion' => 'AV LAS INDUSTRIAS LOCAL GALPON NRO 1 ZONA CONGLOMERADO INDUSTRIAL ALVARO BORTOT             ',
                'correo' => 'cauchoscumanagoto@gmail.com',
                'telefono' => '0414-3931174',
                'activo' => 0,
                'estado' => 0,
                'servidor' => '3.14.204.63',
                'puerto' => '3306',
                'bd' => 'sainta46',
                'usuario' => 'sa',
                'clave' => 'dobermann2021',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => 'J401207448',
            ),
            6 => 
            array (
                'id' => 7,
                'codigo' => 'A41',
                'descripcion' => 'Cauchos La Isla Dorada, S.A.',
                'principal' => 0,
                'direccion' => 'Calle el Proyecto entre calle 2 y Avenida Intercomunal Galpon Nro S/N Zona Industrial       ',
                'correo' => 'cauchoslaisladorada@yahoo.com.ve',
                'telefono' => '0283-2417029    ',
                'activo' => 1,
                'estado' => 0,
                'servidor' => '3.14.204.63',
                'puerto' => '3306',
                'bd' => 'sainta41',
                'usuario' => 'sa',
                'clave' => 'dobermann2021',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => 'J296506655',
            ),
            7 => 
            array (
                'id' => 8,
                'codigo' => 'A03',
                'descripcion' => 'Cauchos Los Llanos, C.A.',
                'principal' => 0,
                'direccion' => 'Calle 30 con Av. Los Agriculto res casa 29-77 Sector El Palito Acarigua/Portuguesa          ',
                'correo' => 'cauchoslosllanosca@gmail.com',
                'telefono' => '0424-5085323 ',
                'activo' => 1,
                'estado' => 0,
                'servidor' => '3.14.204.63',
                'puerto' => '3306',
                'bd' => 'sainta03',
                'usuario' => 'sa',
                'clave' => 'dobermann2021',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => 'J297085696',
            ),
            8 => 
            array (
                'id' => 9,
                'codigo' => 'C91',
                'descripcion' => 'Cauchos Nueva Cadiz, C.A.',
                'principal' => 0,
                'direccion' => 'AV.EL PROGRESO NRO 73-100 ZONA INDUSTRIAL SAN DIEGO VALENCIA EDO CARABOBO                   ',
                'correo' => 'cauchosnuevacadizca@gmail.com',
                'telefono' => '0424-5922402',
                'activo' => 1,
                'estado' => 0,
                'servidor' => '3.14.204.63',
                'puerto' => '3306',
                'bd' => 'saintC91',
                'usuario' => 'sa',
                'clave' => 'dobermann2021',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => 'J299242462',
            ),
            9 => 
            array (
                'id' => 10,
                'codigo' => 'A61',
                'descripcion' => 'Cauchos Panam, S.A.',
                'principal' => 0,
                'direccion' => 'Av. Libertador. Esquina calle 37.Zona Industrial I.
Barquisimeto
(+58) 251-4453052',
                'correo' => 'cauchospanam@gmail.com',
                'telefono' => '0414-5082394',
                'activo' => 0,
                'estado' => 0,
                'servidor' => '3.14.204.63',
                'puerto' => '3306',
                'bd' => 'sainta61',
                'usuario' => 'sa',
                'clave' => 'dobermann2021',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'codigo' => 'A25',
                'descripcion' => 'Centro Caucho Sur Del Lago, C.A.',
                'principal' => 0,
                'direccion' => 'AVENIDA BOLIVAR N?9-10 SECTOR COCO FRIO EL VIGIA EDO MERIDA  
(+58) 0275-8813175 0275-8810896                               ',
                'correo' => 'centrocauchosurdellagosa@gmail.com',
                'telefono' => '0414-7563795',
                'activo' => 1,
                'estado' => 0,
                'servidor' => '3.14.204.63',
                'puerto' => '3306',
                'bd' => 'sainta25',
                'usuario' => 'sa',
                'clave' => 'dobermann2021',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => 'J297273360',
            ),
            11 => 
            array (
                'id' => 12,
                'codigo' => 'A40',
                'descripcion' => 'Comercializadora Rivercauchos, C.A.',
                'principal' => 0,
                'direccion' => 'AV. JORGE RODRIGUEZ RIVERCAUCHOS N? S/N SECTOR LAS GARZAS                                   ',
                'correo' => NULL,
                'telefono' => '0281-2862523    ',
                'activo' => 1,
                'estado' => 0,
                'servidor' => '3.14.204.63',
                'puerto' => '3306',
                'bd' => 'sainta40',
                'usuario' => 'sa',
                'clave' => 'dobermann2021',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => 'J297203087',
            ),
            12 => 
            array (
                'id' => 13,
                'codigo' => 'A68',
                'descripcion' => 'Corcaucho, C.A.',
                'principal' => 0,
                'direccion' => 'AV.LARA LOCAL S/N SECTOR ESTE  BARQUISIMETO EDO. LARA                                       ',
                'correo' => NULL,
                'telefono' => '0251-2550953    ',
                'activo' => 1,
                'estado' => 0,
                'servidor' => NULL,
                'puerto' => NULL,
                'bd' => NULL,
                'usuario' => NULL,
                'clave' => '',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => '  J316218899',
            ),
            13 => 
            array (
                'id' => 14,
                'codigo' => 'A45',
                'descripcion' => 'Corporacion Latinoamericana Del Caucho, S.A.',
                'principal' => 0,
                'direccion' => 'AV.VIA PUENTE ANGOSTURA LOCAL No.S/N SECTOR ANEXO A MIYAKO MOTORS                           ',
                'correo' => NULL,
                'telefono' => '0285-6321573    ',
                'activo' => 1,
                'estado' => 0,
                'servidor' => NULL,
                'puerto' => NULL,
                'bd' => NULL,
                'usuario' => NULL,
                'clave' => '',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => '  J314560220',
            ),
            14 => 
            array (
                'id' => 15,
                'codigo' => 'A36',
                'descripcion' => 'Corporacion Mijacky, C.A.',
                'principal' => 0,
                'direccion' => 'AV. INDUSTRIAL GALPON COVENCAU CHO SECTOR ZONA INDUSTRIAL BARINAS                           ',
                'correo' => NULL,
                'telefono' => '0414-5670303    ',
                'activo' => 1,
                'estado' => 0,
                'servidor' => NULL,
                'puerto' => NULL,
                'bd' => NULL,
                'usuario' => NULL,
                'clave' => '',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => '  J295847440',
            ),
            15 => 
            array (
                'id' => 16,
                'codigo' => 'A47',
                'descripcion' => 'Corporacion Universal del Caucho, C.A.',
                'principal' => 0,
                'direccion' => 'AV. GUMILLA ZONA INDUSTRIAL CHIRICA PARCELA N?123.171.10 SAN FELIX EDO. BOLIVAR             ',
                'correo' => NULL,
                'telefono' => '0286-9943038    ',
                'activo' => 1,
                'estado' => 0,
                'servidor' => NULL,
                'puerto' => NULL,
                'bd' => NULL,
                'usuario' => NULL,
                'clave' => '',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => '  J317014588',
            ),
            16 => 
            array (
                'id' => 17,
                'codigo' => 'A14',
                'descripcion' => 'Cortrucaucho, S.A.',
                'principal' => 0,
                'direccion' => 'AV. BUENOS AIRES C/AV. MEXICO NRO S/N URB LA PLATA JUAN MONT VALERA.ESTADO TRUJILLO         
(+58)0271-2211824 0271-2253497',
                'correo' => 'cortrucaucho@gmail.com',
                'telefono' => '0424-5446244',
                'activo' => 1,
                'estado' => 0,
                'servidor' => '3.14.204.63',
                'puerto' => '3306',
                'bd' => 'sainta14',
                'usuario' => 'sa',
                'clave' => 'dobermann2021',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => 'J298355743',
            ),
            17 => 
            array (
                'id' => 18,
                'codigo' => 'A44',
                'descripcion' => 'Intercauchos Gomez, C.A.',
                'principal' => 0,
                'direccion' => 'Av.Alirio Ugarte Pelayo Nro S/N Sector Bajo Guarapiche Maturin Edo. Monagas                 ',
                'correo' => NULL,
                'telefono' => '0251-6419262    ',
                'activo' => 1,
                'estado' => 0,
                'servidor' => NULL,
                'puerto' => NULL,
                'bd' => NULL,
                'usuario' => NULL,
                'clave' => '',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => '  J316143716',
            ),
            18 => 
            array (
                'id' => 19,
                'codigo' => 'A56',
                'descripcion' => 'Inversiones Lara Tires',
                'principal' => 0,
                'direccion' => 'AV.VENEZUELA CON CALLE 23Y24 EDIF PETILLA,NUMERO 23-74 PISO P/B LOCAL 1 SECTOR CENTRO       ',
                'correo' => NULL,
                'telefono' => '0251-2311671    ',
                'activo' => 1,
                'estado' => 0,
                'servidor' => NULL,
                'puerto' => NULL,
                'bd' => NULL,
                'usuario' => NULL,
                'clave' => '',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => '  J411769029',
            ),
            19 => 
            array (
                'id' => 20,
                'codigo' => 'A90',
                'descripcion' => 'M.P. Cauchos, C.A.',
                'principal' => 0,
                'direccion' => 'AV. PEDRO LEON TORRES CON 50 EDIF. M.P CAUCHOS PISO. LOCAL. ZONA OESTE BARQUISIMETO     
0251-4451668        ',
                'correo' => 'ventas.mpcauchos@gmail.com',
                'telefono' => '0414-3503550',
                'activo' => 1,
                'estado' => 0,
                'servidor' => '3.14.204.63',
                'puerto' => '3306',
                'bd' => 'sainta90',
                'usuario' => 'sa',
                'clave' => 'dobermann2021',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => 'J293495016',
            ),
            20 => 
            array (
                'id' => 21,
                'codigo' => 'A84',
                'descripcion' => 'Multicauchos La Consolacion, S.A.',
                'principal' => 0,
                'direccion' => 'CTRA.PANAMERICANA CON VEREDA 10 LOCAL NRO.10-16 SECTOR EL ABEJAL PALMIRA TACHIRA            ',
                'correo' => NULL,
                'telefono' => '0424-7023578    ',
                'activo' => 1,
                'estado' => 0,
                'servidor' => NULL,
                'puerto' => NULL,
                'bd' => NULL,
                'usuario' => NULL,
                'clave' => '',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => '  J404157522',
            ),
            21 => 
            array (
                'id' => 22,
                'codigo' => 'A65',
                'descripcion' => 'Multiservicios Baricauchos, C.A.',
                'principal' => 0,
                'direccion' => 'CALLE ?E?CARRETERA VIA PUNTA GORDA LOCAL NRO L-3 PUNTA GORDA BARINAS                        ',
                'correo' => NULL,
                'telefono' => '0273-9351187    ',
                'activo' => 1,
                'estado' => 0,
                'servidor' => NULL,
                'puerto' => NULL,
                'bd' => NULL,
                'usuario' => NULL,
                'clave' => '',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => '  J401984509',
            ),
            22 => 
            array (
                'id' => 23,
                'codigo' => 'A28',
                'descripcion' => 'Multiservicios Claros, C.A.',
                'principal' => 0,
                'direccion' => 'CR 13 ENTRE CALLES 34 Y 35 EDIF DON TOTTO PISO LOCAL 1-2 SECTOR CENTRO                      ',
                'correo' => NULL,
                'telefono' => '0414-5399282    ',
                'activo' => 1,
                'estado' => 0,
                'servidor' => NULL,
                'puerto' => NULL,
                'bd' => NULL,
                'usuario' => NULL,
                'clave' => '',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => '  J293558395',
            ),
            23 => 
            array (
                'id' => 24,
                'codigo' => 'A34',
                'descripcion' => 'Neumaticos Carabobo, C.A.',
                'principal' => 0,
                'direccion' => 'AV LISANDRO ALVARADO LOCAL NRO S/N SECTOR LA FLORIDA FRENTE DE A CABEL                      ',
                'correo' => NULL,
                'telefono' => '0241-8315310    ',
                'activo' => 1,
                'estado' => 0,
                'servidor' => NULL,
                'puerto' => NULL,
                'bd' => NULL,
                'usuario' => NULL,
                'clave' => '',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => '  J306451641',
            ),
            24 => 
            array (
                'id' => 25,
                'codigo' => 'A89',
                'descripcion' => 'Lucio Cauchos Los Guaros',
                'principal' => 0,
                'direccion' => 'CALLE PROVIDENCIA ENTRE LIBERTADOR Y ECUADOR LOCAL NRO 14 SECTOR CAJA DE AGUA PUNTO         ',
                'correo' => NULL,
                'telefono' => '0424-7203583    ',
                'activo' => 1,
                'estado' => 0,
                'servidor' => NULL,
                'puerto' => NULL,
                'bd' => NULL,
                'usuario' => NULL,
                'clave' => '',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => '  J500027680',
            ),
            25 => 
            array (
                'id' => 26,
                'codigo' => 'A67',
                'descripcion' => 'Pipe Cauchos, C.A.',
                'principal' => 0,
                'direccion' => 'AV INTERCOMUNAL ENTRE CARRETE- RAS N Y O LOCAL NRO 7662000 SECTOR BARRIO UNION              
0251-6410821  ',
                'correo' => 'pipecauchos@gmail.com',
                'telefono' => '0424-5500850',
                'activo' => 1,
                'estado' => 0,
                'servidor' => '3.14.204.63',
                'puerto' => '3306',
                'bd' => 'sainta67',
                'usuario' => 'sa',
                'clave' => 'dobermann2021',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => 'J403206759',
            ),
            26 => 
            array (
                'id' => 27,
                'codigo' => 'A27',
                'descripcion' => 'Rack Tires de Venezuela, S.A.',
                'principal' => 0,
                'direccion' => 'AV. LIBERTADOR, ESQUINA CALLE 8, LOCAL NRO S/N ZONA INDUSTRI BARQUISIMETO    
0251-2378365                 ',
                'correo' => 'racktiresvzla@gmail.com',
                'telefono' => '0414-6318747',
                'activo' => 1,
                'estado' => 0,
                'servidor' => '3.14.204.63',
                'puerto' => '3306',
                'bd' => 'sainta27',
                'usuario' => 'sa',
                'clave' => 'dobermann2021',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => 'J294598137',
            ),
            27 => 
            array (
                'id' => 28,
                'codigo' => 'A32',
                'descripcion' => 'Servica LP, C.A.',
                'principal' => 0,
                'direccion' => 'Av. Fuerzas Aéreas entre calles Miranda y Av. Bolívar.
Maracay
(+58) 0243-2160101',
                'correo' => 'servicalp@gmail.com',
                'telefono' => '0414-3943644',
                'activo' => 1,
                'estado' => 0,
                'servidor' => '3.14.204.63',
                'puerto' => '3306',
                'bd' => 'sainta32',
                'usuario' => 'sa',
                'clave' => 'dobermann2021',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => 'J296879559',
            ),
            28 => 
            array (
                'id' => 29,
                'codigo' => 'A13',
                'descripcion' => 'Servicauchos Los Andes, S.A.',
                'principal' => 0,
                'direccion' => 'AV. LIBERTADOR NRO. S/N SECTOR LAS LOMAS SAN CRISTOBAL ESTADO TACHIRA                       ',
                'correo' => NULL,
                'telefono' => '0276-3443628    ',
                'activo' => 1,
                'estado' => 0,
                'servidor' => NULL,
                'puerto' => NULL,
                'bd' => NULL,
                'usuario' => NULL,
                'clave' => '',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => '  J294598285',
            ),
            29 => 
            array (
                'id' => 30,
                'codigo' => 'A22',
                'descripcion' => 'Servicauchos Santa Ana, C.A',
                'principal' => 0,
                'direccion' => 'Calle Jaboneria entre Callejon San Miguel y Av. Tirso Salaver Coro.Estado Falcon            ',
                'correo' => NULL,
                'telefono' => '0268-2511954    ',
                'activo' => 1,
                'estado' => 0,
                'servidor' => NULL,
                'puerto' => NULL,
                'bd' => NULL,
                'usuario' => NULL,
                'clave' => '',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => '  J297933522',
            ),
            30 => 
            array (
                'id' => 31,
                'codigo' => 'A57',
                'descripcion' => 'Servicios y Suministros PyF',
                'principal' => 0,
                'direccion' => 'CALLE NEVERI UD-282 MZ 01 PARC 03 LOCAL GALPON NRO.S/N ZONA INDUSTRIAL UNARE GUAYANA        ',
                'correo' => NULL,
                'telefono' => '0414-8671188    ',
                'activo' => 1,
                'estado' => 0,
                'servidor' => NULL,
                'puerto' => NULL,
                'bd' => NULL,
                'usuario' => NULL,
                'clave' => '',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => '  J412592017',
            ),
            31 => 
            array (
                'id' => 32,
                'codigo' => 'A21',
                'descripcion' => 'Super Cauchos Delui, S.A.',
                'principal' => 0,
                'direccion' => 'AV.60 ENTRE AVENIDA 58 Y CALLE 137 LOCAL NRO.58-106 ZONA INDUSTRIAL MARACAIBO ZULIA         
0261-7361691  ',
                'correo' => 'supercauchosdelui@gmail.com',
                'telefono' => '0414-0650179',
                'activo' => 1,
                'estado' => 0,
                'servidor' => '3.14.204.63',
                'puerto' => '3306',
                'bd' => 'sainta21',
                'usuario' => 'sa',
                'clave' => 'dobermann2021',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => 'J293937361',
            ),
            32 => 
            array (
                'id' => 33,
                'codigo' => 'A33',
                'descripcion' => 'Tireland, C.A.',
                'principal' => 0,
                'direccion' => 'AVENIDA PRINCIPAL DEL ALGODONAL N? S/N EL ALGODONAL LA YAGUARA                              ',
                'correo' => NULL,
                'telefono' => '0212-4430708    ',
                'activo' => 1,
                'estado' => 0,
                'servidor' => NULL,
                'puerto' => NULL,
                'bd' => NULL,
                'usuario' => NULL,
                'clave' => '',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => '  J297190384',
            ),
            33 => 
            array (
                'id' => 34,
                'codigo' => 'A92',
                'descripcion' => 'Cauchos La Plata, S.A.',
                'principal' => 0,
                'direccion' => 'CALLE 172 CASA NRO.43-188 URB. LA COROMOTO LOTE 12 ZONA B PARCELA 27 SAN FRANCISCO ZULIA    ',
                'correo' => NULL,
                'telefono' => '0414-3511293    ',
                'activo' => 1,
                'estado' => 0,
                'servidor' => NULL,
                'puerto' => NULL,
                'bd' => NULL,
                'usuario' => NULL,
                'clave' => '',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => '  J412408810',
            ),
            34 => 
            array (
                'id' => 35,
                'codigo' => 'A30',
                'descripcion' => 'Multi Lub & Tire, C.A.',
                'principal' => 0,
                'direccion' => 'AV.LA PAZ LOCAL NRO.GALP?N S/N SECTOR CASCO CENTRAL DE PUERTO CABELLO EDO CARABOBO          ',
                'correo' => NULL,
                'telefono' => '0242-3646263    ',
                'activo' => 1,
                'estado' => 0,
                'servidor' => NULL,
                'puerto' => NULL,
                'bd' => NULL,
                'usuario' => NULL,
                'clave' => '',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => '  J411138045',
            ),
            35 => 
            array (
                'id' => 36,
                'codigo' => 'A91',
                'descripcion' => 'PANAMERICANA DEL CAUCHO 2009, C.A.     ',
                'principal' => 0,
                'direccion' => 'AV.FLORENCIO JIMENEZ CON CALLE 1 LOCAL NRO.13 SECTOR LA CEIBA QUIBOR ESTADO LARA            ',
                'correo' => '',
                'telefono' => '0253-4912484    ',
                'activo' => 1,
                'estado' => 0,
                'servidor' => NULL,
                'puerto' => NULL,
                'bd' => NULL,
                'usuario' => NULL,
                'clave' => '',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => '  J298775084',
            ),
            36 => 
            array (
                'id' => 37,
                'codigo' => 'A93',
                'descripcion' => 'INVERSIONES GILCAR, C.A.               ',
                'principal' => 0,
            'direccion' => 'AV. LAS DELICIAS CALLE 85 (FALCON) LATERAL A LA FORD MARACAIBO EDO. ZULIA                   ',
                'correo' => '',
                'telefono' => '0261-7514696    ',
                'activo' => 1,
                'estado' => 0,
                'servidor' => NULL,
                'puerto' => NULL,
                'bd' => NULL,
                'usuario' => NULL,
                'clave' => '',
                'idUsuario' => 1,
                'created_at' => '2022-01-09 16:25:17',
                'updated_at' => '2022-01-09 16:25:17',
                'rif' => '  J310704406',
            ),
        ));
        
        
    }
}