php artisan iseed ancho --force
php artisan iseed rol --force
php artisan iseed aplicacion --force
php artisan iseed area_defecto --force
php artisan iseed carga_vehiculo --force
php artisan iseed condicion --force
php artisan iseed condicion_caucho --force
php artisan iseed condicion_vehiculo --force
php artisan iseed correlativo --force
php artisan iseed datoscampos --force
php artisan iseed defecto_bolsa_vulcanizacion --force
php artisan iseed defecto_camara --force
php artisan iseed defecto_dvb --force
php artisan iseed defecto_envelop_externo --force
php artisan iseed defecto_envelop_interno --force
php artisan iseed defecto_protector --force
php artisan iseed diagrama_area_defecto --force
php artisan iseed diagrama_caucho --force
php artisan iseed diseno_ancho --force
php artisan iseed diseno_banda --force
php artisan iseed diseno_molde --force
php artisan iseed diseno_profundidad --force --force
php artisan iseed eje_vehiculo --force
php artisan iseed estado --force
php artisan iseed estatus --force
php artisan iseed failed_jobs --force
php artisan iseed marca_camara --force
php artisan iseed marca_caucho --force
php artisan iseed marca_caucho_industrial --force
php artisan iseed marca_protector --force
php artisan iseed marca_vehiculo --force
php artisan iseed medida_camara --force
php artisan iseed medida_caucho --force
php artisan iseed medida_caucho_industrial --force
php artisan iseed migrations --force
php artisan iseed modelo_camara --force
php artisan iseed modelo_caucho --force
php artisan iseed modelo_protector --force
php artisan iseed modelo_vehiculo --force
php artisan iseed pais --force
php artisan iseed password_resets --force
php artisan iseed personal_access_tokens --force
php artisan iseed producto --force
php artisan iseed profundidad --force
php artisan iseed rechazo --force
php artisan iseed rechazo_causa --force
php artisan iseed rechazo_recomendacion --force
php artisan iseed rechazo_zonas --force
